using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HttpBinder.Generator
{
    /// <summary>
    /// Emits the generated binder source for a DTO bound via BindAsync().
    /// Code prioritizes human readability and correct binding semantics.
    /// </summary>
    internal static class CodeRenderer
    {
        // ==================================================================
        //  Render Root
        // ==================================================================

        public static string Render(BoundType model)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            var ns = model.TypeSymbol.ContainingNamespace.ToDisplayString();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            var indent = new IndentedStringBuilder(sb, 1);

            string typeKind = model.TypeSymbol.IsRecord ? "record" : "class";
            indent.AppendLine($"partial {typeKind} {model.TypeSymbol.Name}");
            indent.AppendLine("{");
            indent.Indent();

            RenderBindMethod(indent, model);
            indent.AppendLine();
            RenderComplexHelpers(indent, model);

            indent.Unindent();
            indent.AppendLine("}");

            sb.AppendLine("}");

            return sb.ToString();
        }

        // ==================================================================
        //  BindAsync
        // ==================================================================

        private static void RenderBindMethod(IndentedStringBuilder indent, BoundType model)
        {
            var typeName = Utilities.GetFullTypeName(model.TypeSymbol);
            var requiresForm = RequiresForm(model);

            indent.AppendLine(
                $"public static async global::System.Threading.Tasks.ValueTask<{typeName}> BindAsync(");
            indent.AppendLine("    global::Microsoft.AspNetCore.Http.HttpContext http)");
            indent.AppendLine("{");
            indent.Indent();

            indent.AppendLine("var request = http.Request;");

            if (requiresForm)
                indent.AppendLine("var form = await request.ReadFormAsync().ConfigureAwait(false);");

            indent.AppendLine("var query = request.Query;");
            indent.AppendLine("var route = request.RouteValues;");
            indent.AppendLine();

            foreach (var prop in model.Properties)
            {
                GeneratePropertyBinding(indent, prop, requiresForm);
                indent.AppendLine();
            }

            indent.AppendLine($"var instance = new {typeName}();");

            foreach (var prop in model.Properties)
                indent.AppendLine($"instance.{prop.Name} = {ToCamelCase(prop.Name)};");

            indent.AppendLine("return instance;");

            indent.Unindent();
            indent.AppendLine("}");
        }

        private static bool RequiresForm(BoundType model)
        {
            foreach (var p in model.Properties)
                if (RequiresFormRecursive(p))
                    return true;

            return false;

            static bool RequiresFormRecursive(BoundProperty prop)
            {
                if (prop.HttpBinderType == HttpBinderType.Form)
                    return true;

                foreach (var c in prop.Children)
                    if (RequiresFormRecursive(c))
                        return true;

                return false;
            }
        }

        // ==================================================================
        //  Per-property Binding
        // ==================================================================

        private static void GeneratePropertyBinding(
            IndentedStringBuilder indent,
            BoundProperty prop,
            bool requiresForm)
        {
            string localName = ToCamelCase(prop.Name);
            string typeName = Utilities.GetFullTypeName(prop.Symbol.Type);

            EmitLocalDeclaration(indent, prop, localName, typeName);

            if (prop.IsCollection)
            {
                GenerateCollectionBinding(indent, prop, localName, requiresForm);
                return;
            }

            if (prop.IsComplex)
            {
                EmitComplexCall(indent, prop, localName, requiresForm);
                return;
            }

            EmitSimpleBinding(indent, prop, localName, requiresForm);
        }

        private static void EmitLocalDeclaration(
            IndentedStringBuilder indent,
            BoundProperty prop,
            string localName,
            string typeName)
        {
            if (prop.IsCollection)
            {
                indent.AppendLine($"{typeName} {localName} = new {typeName}();");
                return;
            }

            // Use null-friendly initialization and let parsing fill it
            if (prop.Symbol.Type.IsReferenceType)
            {
                indent.AppendLine($"{typeName}? {localName} = null;");
                return;
            }

            indent.AppendLine($"{typeName} {localName} = default;");
        }

        private static void EmitSimpleBinding(
            IndentedStringBuilder indent,
            BoundProperty prop,
            string localName,
            bool requiresForm)
        {
            string rawVar = $"{localName}Raw";

            EmitValueAccessor(indent, prop, localName, rawVar, requiresForm);
            EmitValueParser(indent, prop, localName, rawVar);
        }

        private static void EmitValueAccessor(
            IndentedStringBuilder indent,
            BoundProperty prop,
            string baseName,
            string rawVar,
            bool requiresForm)
        {
            string key = prop.KeyName;
            string camel = baseName; // already camel-cased
            string formValueVar = $"{camel}FormValue";
            string queryValueVar = $"{camel}QueryValue";
            string routeValueVar = $"{camel}RouteValue";

            switch (prop.HttpBinderType)
            {
                case HttpBinderType.Query:
                    indent.AppendLine(
                        $"var {rawVar} = query.TryGetValue(\"{key}\", out var {queryValueVar}) && {queryValueVar}.Count > 0 ?");
                    indent.AppendLine($"    {queryValueVar}.ToString() : null;");
                    break;

                case HttpBinderType.Route:
                    indent.AppendLine(
                        $"var {rawVar} = route.TryGetValue(\"{key}\", out var {routeValueVar}) ? {routeValueVar}?.ToString() : null;");
                    break;

                case HttpBinderType.Form:
                default:
                    if (requiresForm)
                    {
                        indent.AppendLine(
                            $"var {rawVar} = form.TryGetValue(\"{key}\", out var {formValueVar}) && {formValueVar}.Count > 0 ?");
                        indent.AppendLine($"    {formValueVar}.ToString() : null;");
                    }
                    else
                    {
                        indent.AppendLine(
                            $"var {rawVar} = http.Request.Form.TryGetValue(\"{key}\", out var {formValueVar}) && {formValueVar}.Count > 0 ?");
                        indent.AppendLine($"    {formValueVar}.ToString() : null;");
                    }
                    break;
            }
        }

        private static void EmitValueParser(
            IndentedStringBuilder indent,
            BoundProperty prop,
            string localName,
            string rawVar)
        {
            if (prop.IsString)
            {
                // Avoid nullable warning by guarding assignment
                indent.AppendLine($"if ({rawVar} != null) {localName} = {rawVar};");
                return;
            }

            if (prop.IsGuid)
            {
                indent.AppendLine(
                    $"if ({rawVar} != null && global::System.Guid.TryParse({rawVar}, out var {localName}Parsed))");
                indent.AppendLine($"    {localName} = {localName}Parsed;");
                return;
            }

            if (prop.IsEnum)
            {
                var enumName = Utilities.GetFullTypeName(prop.Symbol.Type);

                indent.AppendLine(
                    $"if ({rawVar} != null && global::System.Enum.TryParse<{enumName}>({rawVar}, true, out var {localName}Parsed))");
                indent.AppendLine($"    {localName} = {localName}Parsed;");
                return;
            }

            if (prop.IsPrimitive)
            {
                string parse = GetTryParseMethod(prop.Symbol.Type);

                indent.AppendLine(
                    $"if ({rawVar} != null && {parse}({rawVar}, out var {localName}Parsed))");
                indent.AppendLine($"    {localName} = {localName}Parsed;");
                return;
            }

            indent.AppendLine($"// Unsupported type: {Utilities.GetFullTypeName(prop.Symbol.Type)}");
        }

        private static void EmitComplexCall(
            IndentedStringBuilder indent,
            BoundProperty prop,
            string localName,
            bool requiresForm)
        {
            string helperName = $"Bind_{GetSanitizedTypeName(prop.Symbol.Type)}";
            string formArg = requiresForm ? "form" : "null";
            string prefix = prop.KeyName + ".";

            indent.AppendLine(
                $"{localName} = {helperName}(http, \"{prefix}\", {formArg}, query, route);");
        }

        // ==================================================================
        //  Collection Binding
        // ==================================================================

        private static void GenerateCollectionBinding(
            IndentedStringBuilder indent,
            BoundProperty prop,
            string localName,
            bool requiresForm)
        {
            string listName = localName;
            var elementType = prop.CollectionType!;
            string keyBase = prop.KeyName;

            string keysExpr =
                prop.HttpBinderType == HttpBinderType.Query ? "query.Keys" :
                prop.HttpBinderType == HttpBinderType.Route ? "route.Keys" :
                requiresForm ? "form.Keys" :
                "http.Request.Form.Keys";

            indent.AppendLine($"var {listName}Prefix = \"{keyBase}[\";");

            indent.AppendLine();
            indent.AppendLine($"foreach (var key in {keysExpr})");
            indent.AppendLine("{");
            indent.Indent();

            indent.AppendLine(
                $"if (!key.StartsWith({listName}Prefix, global::System.StringComparison.OrdinalIgnoreCase)) continue;");

            indent.AppendLine($"var {listName}IndexStart = {listName}Prefix.Length;");
            indent.AppendLine($"var {listName}IndexEnd = key.IndexOf(']', {listName}IndexStart);");
            indent.AppendLine($"if ({listName}IndexEnd < 0) continue;");

            indent.AppendLine($"var {listName}IndexString = key.Substring({listName}IndexStart, {listName}IndexEnd - {listName}IndexStart);");
            indent.AppendLine($"if (!int.TryParse({listName}IndexString, out var {listName}Index)) continue;");

            indent.AppendLine($"while ({listName}.Count <= {listName}Index) {listName}.Add(default!);");

            indent.AppendLine("var elementKey = key;");

            bool elementIsSimple = IsSimpleElementType(elementType);

            if (!elementIsSimple)
            {
                string helperName = $"Bind_{GetSanitizedTypeName(elementType)}";
                string formArg = requiresForm ? "form" : "null";

                indent.AppendLine(
                    $"{listName}[{listName}Index] = {helperName}(http, elementKey + \".\", {formArg}, query, route);");
            }
            else
            {
                EmitCollectionElementBinding(indent, listName, ToCamelCase(listName), elementType, prop.HttpBinderType);
            }

            indent.Unindent();
            indent.AppendLine("}");
        }

        private static void EmitCollectionElementBinding(
            IndentedStringBuilder indent,
            string listName,
            string baseName,
            ITypeSymbol elementType,
            HttpBinderType binderType)
        {
            string rawVar = $"{baseName}ElementRaw";
            string formValueVar = $"{baseName}ElementFormValue";
            string queryValueVar = $"{baseName}ElementQueryValue";
            string routeValueVar = $"{baseName}ElementRouteValue";

            indent.AppendLine();
            indent.AppendLine($"string? {rawVar} = null;");

            switch (binderType)
            {
                case HttpBinderType.Query:
                    indent.AppendLine(
                        $"if (query.TryGetValue(elementKey, out var {queryValueVar}) && {queryValueVar}.Count > 0)");
                    indent.AppendLine($"    {rawVar} = {queryValueVar}.ToString();");
                    break;

                case HttpBinderType.Route:
                    indent.AppendLine(
                        $"if (route.TryGetValue(elementKey, out var {routeValueVar}))");
                    indent.AppendLine($"    {rawVar} = {routeValueVar}?.ToString();");
                    break;

                case HttpBinderType.Form:
                default:
                    indent.AppendLine(
                        $"if (form!.TryGetValue(elementKey, out var {formValueVar}) && {formValueVar}.Count > 0)");
                    indent.AppendLine($"    {rawVar} = {formValueVar}.ToString();");
                    break;
            }

            indent.AppendLine();

            string full = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (full == "global::System.String")
            {
                indent.AppendLine($"if ({rawVar} != null) {listName}[{listName}Index] = {rawVar};");
                return;
            }

            if (full == "global::System.Guid")
            {
                indent.AppendLine(
                    $"if ({rawVar} != null && global::System.Guid.TryParse({rawVar}, out var elementParsed))");
                indent.AppendLine($"    {listName}[{listName}Index] = elementParsed;");
                return;
            }

            if (elementType is INamedTypeSymbol enumType && enumType.TypeKind == TypeKind.Enum)
            {
                string enumName = Utilities.GetFullTypeName(elementType);

                indent.AppendLine(
                    $"if ({rawVar} != null && global::System.Enum.TryParse<{enumName}>({rawVar}, true, out var elementParsed))");
                indent.AppendLine($"    {listName}[{listName}Index] = elementParsed;");
                return;
            }

            string parse = GetTryParseMethod(elementType);

            indent.AppendLine(
                $"if ({rawVar} != null && {parse}({rawVar}, out var elementParsed))");
            indent.AppendLine($"    {listName}[{listName}Index] = elementParsed;");
        }

        // ==================================================================
        //  Complex-Type Helpers
        // ==================================================================

        private static void RenderComplexHelpers(IndentedStringBuilder indent, BoundType model)
        {
            var emitted = new HashSet<string>(StringComparer.Ordinal);

            void Process(BoundProperty prop)
            {
                if (prop.IsComplex && !prop.IsCollection)
                {
                    string key = GetSanitizedTypeName(prop.Symbol.Type);
                    if (emitted.Add(key))
                        RenderComplexHelper(indent, prop.Symbol.Type, prop.Children);
                }

                if (prop.CollectionType is ITypeSymbol element &&
                    NeedsComplexHelper(element))
                {
                    string key = GetSanitizedTypeName(element);
                    if (emitted.Add(key))
                        RenderComplexHelper(indent, element, prop.Children);
                }

                foreach (var c in prop.Children)
                    Process(c);
            }

            foreach (var p in model.Properties)
                Process(p);
        }

        private static bool NeedsComplexHelper(ITypeSymbol type)
        {
            return !IsSimpleElementType(type);
        }

        private static void RenderComplexHelper(
            IndentedStringBuilder indent,
            ITypeSymbol type,
            List<BoundProperty> children)
        {
            string typeName = Utilities.GetFullTypeName(type);
            string helperName = $"Bind_{GetSanitizedTypeName(type)}";

            indent.AppendLine($"private static {typeName} {helperName}(");
            indent.AppendLine("    global::Microsoft.AspNetCore.Http.HttpContext http,");
            indent.AppendLine("    string prefix,");
            indent.AppendLine("    global::Microsoft.AspNetCore.Http.IFormCollection? form,");
            indent.AppendLine("    global::Microsoft.AspNetCore.Http.IQueryCollection query,");
            indent.AppendLine("    global::Microsoft.AspNetCore.Routing.RouteValueDictionary route)");
            indent.AppendLine("{");
            indent.Indent();

            // Locals
            foreach (var c in children)
            {
                string localName = ToCamelCase(c.Name);
                string childTypeName = Utilities.GetFullTypeName(c.Symbol.Type);

                if (c.IsCollection)
                {
                    indent.AppendLine($"{childTypeName} {localName} = new {childTypeName}();");
                }
                else
                {
                    string initializer =
                        (c.IsNullable || c.Symbol.Type.IsReferenceType)
                        ? "default!"
                        : "default";

                    indent.AppendLine($"{childTypeName} {localName} = {initializer};");
                }
            }

            indent.AppendLine();

            // Binding logic
            foreach (var c in children)
            {
                var localName = ToCamelCase(c.Name);
                var keyVar = $"{localName}Key";

                indent.AppendLine($"// {c.Name}");
                indent.AppendLine($"var {keyVar} = prefix + \"{c.KeyName}\";");
                indent.AppendLine();

                if (c.IsCollection)
                {
                    EmitComplexChildCollection(indent, c, localName, keyVar);
                }
                else if (c.IsComplex)
                {
                    string nestedHelper = $"Bind_{GetSanitizedTypeName(c.Symbol.Type)}";
                    indent.AppendLine(
                        $"{localName} = {nestedHelper}(http, {keyVar} + \".\", form, query, route);");
                }
                else
                {
                    EmitComplexChildSimple(indent, c, localName, keyVar);
                }

                indent.AppendLine();
            }

            string instanceName = "instance";
            indent.AppendLine($"var {instanceName} = new {typeName}();");

            foreach (var c in children)
            {
                string localName = ToCamelCase(c.Name);
                indent.AppendLine($"{instanceName}.{c.Name} = {localName};");
            }

            indent.AppendLine($"return {instanceName};");

            indent.Unindent();
            indent.AppendLine("}");
        }

        private static void EmitComplexChildSimple(
            IndentedStringBuilder indent,
            BoundProperty child,
            string localName,
            string keyVar)
        {
            string rawVar = $"{localName}Raw";
            string formValueVar = $"{localName}FormValue";
            string queryValueVar = $"{localName}QueryValue";
            string routeValueVar = $"{localName}RouteValue";

            switch (child.HttpBinderType)
            {
                case HttpBinderType.Query:
                    indent.AppendLine(
                        $"var {rawVar} = query.TryGetValue({keyVar}, out var {queryValueVar}) && {queryValueVar}.Count > 0 ?");
                    indent.AppendLine($"    {queryValueVar}.ToString() : null;");
                    break;

                case HttpBinderType.Route:
                    indent.AppendLine(
                        $"var {rawVar} = route.TryGetValue({keyVar}, out var {routeValueVar}) ? {routeValueVar}?.ToString() : null;");
                    break;

                case HttpBinderType.Form:
                default:
                    indent.AppendLine(
                        $"var {rawVar} = form != null && form.TryGetValue({keyVar}, out var {formValueVar}) && {formValueVar}.Count > 0 ?");
                    indent.AppendLine($"    {formValueVar}.ToString() : null;");
                    break;
            }

            EmitValueParser(indent, child, localName, rawVar);
        }

        private static void EmitComplexChildCollection(
            IndentedStringBuilder indent,
            BoundProperty child,
            string localName,
            string keyVar)
        {
            string prefixVar = $"{localName}Prefix";

            indent.AppendLine($"var {prefixVar} = {keyVar} + \"[\";");

            indent.AppendLine();
            indent.AppendLine("foreach (var key in form?.Keys ?? global::System.Array.Empty<string>())");
            indent.AppendLine("{");
            indent.Indent();

            indent.AppendLine(
                $"if (!key.StartsWith({prefixVar}, global::System.StringComparison.OrdinalIgnoreCase)) continue;");

            indent.AppendLine($"var {localName}IndexStart = {prefixVar}.Length;");
            indent.AppendLine($"var {localName}IndexEnd = key.IndexOf(']', {localName}IndexStart);");
            indent.AppendLine($"if ({localName}IndexEnd < 0) continue;");

            indent.AppendLine($"var {localName}IndexString = key.Substring({localName}IndexStart, {localName}IndexEnd - {localName}IndexStart);");
            indent.AppendLine($"if (!int.TryParse({localName}IndexString, out var {localName}Index)) continue;");

            indent.AppendLine($"while ({localName}.Count <= {localName}Index) {localName}.Add(default!);");

            indent.AppendLine("var elementKey = key;");

            if (child.CollectionType is ITypeSymbol elementType)
            {
                bool elementIsSimple = IsSimpleElementType(elementType);

                if (!elementIsSimple)
                {
                    string nestedHelper = $"Bind_{GetSanitizedTypeName(elementType)}";
                    indent.AppendLine(
                        $"{localName}[{localName}Index] = {nestedHelper}(http, elementKey + \".\", form, query, route);");
                }
                else
                {
                    EmitCollectionElementBinding(
                        indent,
                        localName,
                        localName,
                        elementType,
                        child.HttpBinderType);
                }
            }

            indent.Unindent();
            indent.AppendLine("}");
        }

        // ==================================================================
        //  Helpers
        // ==================================================================

        private static string GetSanitizedTypeName(ITypeSymbol type)
        {
            string raw = Utilities.GetMinimalTypeName(type);
            var sb = new StringBuilder(raw.Length);

            foreach (char c in raw)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');

            return sb.ToString();
        }

        private static string GetTryParseMethod(ITypeSymbol type)
        {
            string t = Utilities.GetFullTypeName(type);

            return t switch
            {
                "global::System.Boolean" => "bool.TryParse",
                "global::System.Byte" => "byte.TryParse",
                "global::System.SByte" => "sbyte.TryParse",
                "global::System.Int16" => "short.TryParse",
                "global::System.UInt16" => "ushort.TryParse",
                "global::System.Int32" => "int.TryParse",
                "global::System.UInt32" => "uint.TryParse",
                "global::System.Int64" => "long.TryParse",
                "global::System.UInt64" => "ulong.TryParse",
                "global::System.Single" => "float.TryParse",
                "global::System.Double" => "double.TryParse",
                "global::System.Decimal" => "decimal.TryParse",
                _ => "int.TryParse"
            };
        }

        private static bool IsSimpleElementType(ITypeSymbol type)
        {
            // unwrap Nullable<T>
            if (type is INamedTypeSymbol named &&
                named.IsGenericType &&
                named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            {
                type = named.TypeArguments[0];
            }

            if (type.SpecialType == SpecialType.System_String)
                return true;

            if (type is INamedTypeSymbol n && n.TypeKind == TypeKind.Enum)
                return true;

            var full = Utilities.GetFullTypeName(type);
            if (full == "global::System.Guid")
                return true;

            if (type.SpecialType is
                SpecialType.System_Boolean or
                SpecialType.System_Byte or
                SpecialType.System_SByte or
                SpecialType.System_Int16 or
                SpecialType.System_UInt16 or
                SpecialType.System_Int32 or
                SpecialType.System_UInt32 or
                SpecialType.System_Int64 or
                SpecialType.System_UInt64 or
                SpecialType.System_Single or
                SpecialType.System_Double or
                SpecialType.System_Decimal or
                SpecialType.System_Char)
                return true;

            return false;
        }

        private static string ToCamelCase(string name)
        {
            if (string.IsNullOrEmpty(name))
                return name;

            if (char.IsLower(name[0]))
                return name;

            return char.ToLowerInvariant(name[0]) + name.Substring(1);
        }
    }
}
