using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HttpBinder.Generator
{
    /// <summary>
    /// Responsible for emitting the C# source code of the binder for a given
    /// bound type. The generated source follows idiomatic C# style and
    /// introduces helper methods as necessary to perform recursive binding.
    /// </summary>
    internal static class CodeRenderer
    {
        /// <summary>
        /// Emits the binder code for the provided <see cref="BoundType"/>.
        /// </summary>
        /// <param name="model">The bound model for which to emit code.</param>
        /// <returns>The generated C# source as a string.</returns>
        public static string Render(BoundType model)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            var typeSymbol = model.TypeSymbol;
            var ns = typeSymbol.ContainingNamespace.ToDisplayString();
            if (!string.IsNullOrEmpty(ns) && ns != "<global namespace>")
            {
                sb.Append("namespace ").AppendLine(ns).AppendLine("{");
            }
            var indentLevel = (!string.IsNullOrEmpty(ns) && ns != "<global namespace>") ? 1 : 0;
            var indent = new IndentedStringBuilder(sb, indentLevel);
            var typeKindKeyword = typeSymbol.IsRecord
                ? "record"
                : "class"
            indent.AppendLine($"partial {typeKindKeyword} {typeSymbol.Name}");
            indent.AppendLine("{");
            indent.Indent();
            // Render the main BindAsync method
            RenderBindMethod(indent, model);
            // Render any helper methods required for nested complex types
            RenderComplexHelpers(indent, model);
            indent.Unindent();
            indent.AppendLine("}");
            if (!string.IsNullOrEmpty(ns) && ns != "<global namespace>")
            {
                sb.AppendLine("}");
            }
            return sb.ToString();
        }

        private static void RenderBindMethod(IndentedStringBuilder indent, BoundType model)
        {
            var typeName = model.TypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            indent.AppendLine($"public static async System.Threading.Tasks.ValueTask<{typeName}> BindAsync(Microsoft.AspNetCore.Http.HttpContext ctx)");
            indent.AppendLine("{");
            indent.Indent();
            // Determine if we need to read the form from the request. We only read
            // it once even if multiple properties come from the form.
            var formNeeded = model.Properties.Any(p => p.Source == SourceKind.Form);
            if (formNeeded)
            {
                indent.AppendLine("var form = await ctx.Request.ReadFormAsync().ConfigureAwait(false);");
            }
            indent.AppendLine("var query = ctx.Request.Query;");
            indent.AppendLine("var route = ctx.Request.RouteValues;");
            indent.AppendLine();
            // Declare and bind each property
            foreach (var prop in model.Properties)
            {
                GeneratePropertyBinding(indent, prop, formNeeded);
            }
            indent.AppendLine();
            // Instantiate the DTO either via a constructor or default constructor
            if (model.Constructor != null && model.Constructor.Parameters.Length > 0)
            {
                // Constructor initialisation
                indent.Append($"var result = new {GetTypeName(model.TypeSymbol)}(");
                indent.AppendLine();
                indent.Indent();
                for (int i = 0; i < model.Constructor.Parameters.Length; i++)
                {
                    var mapping = model.ConstructorMapping[i];
                    var propName = mapping.property.Name;
                    if (i < model.Constructor.Parameters.Length - 1)
                    {
                        indent.AppendLine($"{propName},");
                    }
                    else
                    {
                        indent.AppendLine($"{propName}");
                    }
                }
                indent.Unindent();
                indent.AppendLine(");");
                // Assign remaining properties not mapped through the constructor
                var remaining = model.Properties.Where(p => !model.ConstructorMapping.Any(m => m.property == p));
                foreach (var prop in remaining)
                {
                    indent.AppendLine($"result.{prop.Name} = {prop.Name};");
                }
                indent.AppendLine("return new(result);");
            }
            else
            {
                // Parameterless constructor path
                indent.AppendLine($"var result = new {GetTypeName(model.TypeSymbol)}();");
                foreach (var prop in model.Properties)
                {
                    indent.AppendLine($"result.{prop.Name} = {prop.Name};");
                }
                indent.AppendLine("return new(result);");
            }
            indent.Unindent();
            indent.AppendLine("}");
        }

        private static void GeneratePropertyBinding(IndentedStringBuilder indent, BoundProperty prop, bool formNeeded)
        {
            var varName = prop.Name;
            var typeName = GetTypeName(prop.Symbol.Type);
            // Declare the variable and assign an initial default
            indent.Append($"{typeName} {varName} = ");
            if (prop.IsCollection)
            {
                indent.AppendLine($"new {typeName}();");
            }
            else if (prop.IsNullable || prop.Symbol.Type.IsReferenceType)
            {
                indent.AppendLine("default!;");
            }
            else
            {
                indent.AppendLine("default;");
            }
            // Begin binding scope
            indent.AppendLine("{");
            indent.Indent();
            // Handle collections
            if (prop.IsCollection)
            {
                GenerateCollectionBinding(indent, prop, formNeeded);
            }
            else if (prop.IsComplex)
            {
                // Delegate to helper for nested complex type
                var helperName = $"Bind_{GetSanitisedTypeName(prop.Symbol.Type)}";
                var formArg = formNeeded ? "form" : "null";
                indent.AppendLine($"{varName} = {helperName}(ctx, \"{prop.KeyName}.\", {formArg}, query, route);");
            }
            else
            {
                // Bind simple value (primitive, string, enum, guid)
                // Determine the value string based on the source
                var valueVar = $"value_{varName}";
                switch (prop.Source)
                {
                    case SourceKind.Query:
                        indent.AppendLine($"var {valueVar} = query[\"{prop.KeyName}\"].Count > 0 ? query[\"{prop.KeyName}\"].ToString() : null;");
                        break;
                    case SourceKind.Route:
                        indent.AppendLine($"var {valueVar} = route.TryGetValue(\"{prop.KeyName}\", out var tmp_{varName}) ? tmp_{varName}?.ToString() : null;");
                        break;
                    case SourceKind.Form:
                    default:
                        if (formNeeded)
                        {
                            indent.AppendLine($"var {valueVar} = form[\"{prop.KeyName}\"].Count > 0 ? form[\"{prop.KeyName}\"].ToString() : null;");
                        }
                        else
                        {
                            indent.AppendLine($"var {valueVar} = ctx.Request.Form[\"{prop.KeyName}\"].Count > 0 ? ctx.Request.Form[\"{prop.KeyName}\"].ToString() : null;");
                        }
                        break;
                }
                // Assign based on type
                if (prop.IsString)
                {
                    indent.AppendLine($"{varName} = {valueVar};");
                }
                else if (prop.IsGuid)
                {
                    indent.AppendLine($"if ({valueVar} != null && System.Guid.TryParse({valueVar}, out var guidResult)) {varName} = guidResult;");
                }
                else if (prop.IsEnum)
                {
                    var enumTypeName = GetTypeName(prop.Symbol.Type);
                    indent.AppendLine($"if ({valueVar} != null && System.Enum.TryParse<{enumTypeName}>({valueVar}, true, out var enumResult)) {varName} = enumResult;");
                }
                else if (prop.IsPrimitive)
                {
                    var tryParse = GetTryParseMethod(prop.Symbol.Type);
                    indent.AppendLine($"if ({valueVar} != null && {tryParse}({valueVar}, out var parsedValue)) {varName} = parsedValue;");
                }
                else
                {
                    indent.AppendLine($"// Unsupported simple type {typeName}, value ignored");
                }
            }
            indent.Unindent();
            indent.AppendLine("}");
        }

        private static void GenerateSimpleBinding(IndentedStringBuilder indent, BoundProperty prop, string valueAccessor)
        {
            // Implementation will be filled in below
        }

        private static void GenerateCollectionBinding(IndentedStringBuilder indent, BoundProperty prop, bool formNeeded)
        {
            var varName = prop.Name;
            // Determine which source to enumerate keys from
            string keysAccessor;
            switch (prop.Source)
            {
                case SourceKind.Query:
                    keysAccessor = "query.Keys";
                    break;
                case SourceKind.Route:
                    keysAccessor = "route.Keys";
                    break;
                case SourceKind.Form:
                default:
                    keysAccessor = formNeeded ? "form.Keys" : "ctx.Request.Form.Keys";
                    break;
            }
            // Start iteration over keys
            indent.AppendLine($"var prefixCollection = \"{prop.KeyName}[\";");
            indent.AppendLine($"foreach (var key in {keysAccessor})");
            indent.AppendLine("{");
            indent.Indent();
            indent.AppendLine("if (!key.StartsWith(prefixCollection, StringComparison.OrdinalIgnoreCase)) continue;");
            indent.AppendLine("var idxStart = prefixCollection.Length;");
            indent.AppendLine("var idxEnd = key.IndexOf(']', idxStart);");
            indent.AppendLine("if (idxEnd < 0) continue;");
            indent.AppendLine("var indexStr = key.Substring(idxStart, idxEnd - idxStart);");
            indent.AppendLine("if (!int.TryParse(indexStr, out var index)) continue;");
            indent.AppendLine($"while ({varName}.Count <= index) {{ {varName}.Add(default!); }}");
            // Determine element key prefix
            indent.AppendLine($"var elementPrefix = \"{prop.KeyName}[\" + index + \"].\";");
            if (!prop.IsComplex)
            {
                var elemType = prop.ElementType!;
                var elemValueVar = $"elemValue_{varName}";
                // Determine value accessor for element
                switch (prop.Source)
                {
                    case SourceKind.Query:
                        indent.AppendLine($"var {elemValueVar} = query[elementPrefix.TrimEnd('.')].Count > 0 ? query[elementPrefix.TrimEnd('.')].ToString() : null;");
                        break;
                    case SourceKind.Route:
                        indent.AppendLine($"var {elemValueVar} = route.TryGetValue(elementPrefix.TrimEnd('.'), out var tmp_{varName}) ? tmp_{varName}?.ToString() : null;");
                        break;
                    case SourceKind.Form:
                    default:
                        if (formNeeded)
                        {
                            indent.AppendLine($"var {elemValueVar} = form[elementPrefix.TrimEnd('.')].Count > 0 ? form[elementPrefix.TrimEnd('.')].ToString() : null;");
                        }
                        else
                        {
                            indent.AppendLine($"var {elemValueVar} = ctx.Request.Form[elementPrefix.TrimEnd('.')].Count > 0 ? ctx.Request.Form[elementPrefix.TrimEnd('.')].ToString() : null;");
                        }
                        break;
                }
                // Parse element value based on element type
                var elemTypeName = GetTypeName(elemType);
                if (elemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.String")
                {
                    indent.AppendLine($"{varName}[index] = {elemValueVar};");
                }
                else if (elemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Guid")
                {
                    indent.AppendLine($"if ({elemValueVar} != null && System.Guid.TryParse({elemValueVar}, out var g)) {varName}[index] = g;");
                }
                else if (elemType is INamedTypeSymbol nts && nts.TypeKind == TypeKind.Enum)
                {
                    var enumTypeName = elemTypeName;
                    indent.AppendLine($"if ({elemValueVar} != null && System.Enum.TryParse<{enumTypeName}>({elemValueVar}, true, out var e)) {varName}[index] = e;");
                }
                else
                {
                    var tryParse = GetTryParseMethod(elemType);
                    indent.AppendLine($"if ({elemValueVar} != null && {tryParse}({elemValueVar}, out var pv)) {varName}[index] = pv;");
                }
            }
            else
            {
                // Complex element type: call helper with prefix
                var helperName = $"Bind_{GetSanitisedTypeName(prop.ElementType!)}";
                indent.AppendLine($"{varName}[index] = {helperName}(ctx, elementPrefix, {(formNeeded ? "form" : "null")}, query, route);");
            }
            indent.Unindent();
            indent.AppendLine("}");
        }

        private static string GetTypeName(ITypeSymbol typeSymbol)
        {
            return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        private static string GetSanitisedTypeName(ITypeSymbol symbol)
        {
            var name = symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            var sb = new StringBuilder();
            foreach (var ch in name)
            {
                if (char.IsLetterOrDigit(ch)) sb.Append(ch);
                else sb.Append('_');
            }
            return sb.ToString();
        }

        private static string GetTryParseMethod(ITypeSymbol type)
        {
            var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return name switch
            {
                "global::System.Boolean" => "bool.TryParse",
                "global::System.Byte" => "byte.TryParse",
                "global::System.SByte" => "sbyte.TryParse",
                "global::System.Int16" => "short.TryParse",
                "global::System.UInt16" => "ushort.TryParse",
                "global::System.Int32" => "int.TryParse",
                "global::System.UInt32" => "uint.TryParse",
                "global::System.Int64" => "long.TryParse",
                "global::System.UInt64" => "ulong.TryParse",
                "global::System.Single" => "float.TryParse",
                "global::System.Double" => "double.TryParse",
                "global::System.Decimal" => "decimal.TryParse",
                _ => "int.TryParse"
            };
        }

        private static string GetDefaultExpression(BoundProperty prop)
        {
            if (prop.IsNullable || prop.Symbol.Type.IsReferenceType)
            {
                return "default!";
            }
            return "default";
        }

        /// <summary>
        /// Emits helper methods used to bind nested complex types. For every
        /// complex property encountered in the bound type (including within
        /// collections) this routine generates a private static method that
        /// accepts a key prefix and reads values from the form, query or route
        /// collections accordingly. Each helper uses a parameterless
        /// constructor to instantiate the nested type and populates its
        /// properties based on the discovered children of the corresponding
        /// <see cref="BoundProperty"/>. Helper methods are only emitted
        /// once per unique complex type.
        /// </summary>
        private static void RenderComplexHelpers(IndentedStringBuilder indent, BoundType model)
        {
            var processed = new HashSet<string>(StringComparer.Ordinal);

            void ProcessProperty(BoundProperty property)
            {
                if (property.IsComplex)
                {
                    var typeSymbol = property.Symbol.Type;
                    var sanitized = GetSanitisedTypeName(typeSymbol);
                    if (!processed.Contains(sanitized))
                    {
                        processed.Add(sanitized);
                        RenderComplexHelper(indent, typeSymbol, property.Children);
                    }
                    foreach (var child in property.Children)
                    {
                        ProcessProperty(child);
                    }
                }
                if (property.IsCollection && property.ElementType != null)
                {
                    var elemType = property.ElementType;
                    // heuristically determine if element is complex
                    var elemIsEnum = elemType is INamedTypeSymbol nts && nts.TypeKind == TypeKind.Enum;
                    var elemIsGuid = elemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Guid";
                    var elemIsString = elemType.SpecialType == SpecialType.System_String;
                    var elemIsPrimitive = elemType is INamedTypeSymbol named && named.SpecialType != SpecialType.None && named.SpecialType != SpecialType.System_String;
                    if (!elemIsEnum && !elemIsGuid && !elemIsString && !elemIsPrimitive)
                    {
                        var sanitizedElem = GetSanitisedTypeName(elemType);
                        if (!processed.Contains(sanitizedElem))
                        {
                            processed.Add(sanitizedElem);
                            RenderComplexHelper(indent, elemType, property.Children);
                        }
                    }
                }
            }
            foreach (var prop in model.Properties)
            {
                ProcessProperty(prop);
            }
        }

        /// <summary>
        /// Generates a helper method for binding a specific complex type. The
        /// helper accepts a prefix string which is prepended to each child
        /// property name when looking up values in the HTTP sources.
        /// </summary>
        private static void RenderComplexHelper(IndentedStringBuilder indent, ITypeSymbol typeSymbol, List<BoundProperty> children)
        {
            var typeName = GetTypeName(typeSymbol);
            var sanitized = GetSanitisedTypeName(typeSymbol);
            var helperName = $"Bind_{sanitized}";
            // Method signature
            indent.AppendLine($"private static {typeName} {helperName}(Microsoft.AspNetCore.Http.HttpContext ctx, string prefix, Microsoft.AspNetCore.Http.IFormCollection? form, Microsoft.AspNetCore.Http.IQueryCollection query, Microsoft.AspNetCore.Routing.RouteValueDictionary route)");
            indent.AppendLine("{");
            indent.Indent();
            // Declare variables for child properties
            foreach (var child in children)
            {
                var childTypeName = GetTypeName(child.Symbol.Type);
                if (child.IsCollection)
                {
                    indent.AppendLine($"{childTypeName} {child.Name} = new {childTypeName}();");
                }
                else if (child.IsNullable || child.Symbol.Type.IsReferenceType)
                {
                    indent.AppendLine($"{childTypeName} {child.Name} = default!;");
                }
                else
                {
                    indent.AppendLine($"{childTypeName} {child.Name} = default;");
                }
            }
            // Bind each child property
            foreach (var child in children)
            {
                indent.AppendLine("{");
                indent.Indent();
                var fullKeyVar = $"key_{GetSanitisedTypeName(child.Symbol.Type)}_{child.Name}";
                indent.AppendLine($"var {fullKeyVar} = prefix + \"{child.KeyName}\";");
                if (!child.IsCollection)
                {
                    var valueVar = $"value_{child.Name}";
                    // Determine accessor for the child's source
                    switch (child.Source)
                    {
                        case SourceKind.Query:
                            indent.AppendLine($"var {valueVar} = query[{fullKeyVar}].Count > 0 ? query[{fullKeyVar}].ToString() : null;");
                            break;
                        case SourceKind.Route:
                            indent.AppendLine($"var {valueVar} = route.TryGetValue({fullKeyVar}, out var tmp_{child.Name}) ? tmp_{child.Name}?.ToString() : null;");
                            break;
                        case SourceKind.Form:
                        default:
                            indent.AppendLine($"var {valueVar} = form != null && form[{fullKeyVar}].Count > 0 ? form[{fullKeyVar}].ToString() : null;");
                            break;
                    }
                    if (child.IsComplex)
                    {
                        var nestedHelper = $"Bind_{GetSanitisedTypeName(child.Symbol.Type)}";
                        indent.AppendLine($"{child.Name} = {nestedHelper}(ctx, {fullKeyVar} + \".\", form, query, route);");
                    }
                    else if (child.IsString)
                    {
                        indent.AppendLine($"{child.Name} = {valueVar};");
                    }
                    else if (child.IsGuid)
                    {
                        indent.AppendLine($"if ({valueVar} != null && System.Guid.TryParse({valueVar}, out var guidResult)) {child.Name} = guidResult;");
                    }
                    else if (child.IsEnum)
                    {
                        var enumTypeName = GetTypeName(child.Symbol.Type);
                        indent.AppendLine($"if ({valueVar} != null && System.Enum.TryParse<{enumTypeName}>({valueVar}, true, out var enumResult)) {child.Name} = enumResult;");
                    }
                    else if (child.IsPrimitive)
                    {
                        var tryParse = GetTryParseMethod(child.Symbol.Type);
                        indent.AppendLine($"if ({valueVar} != null && {tryParse}({valueVar}, out var parsedValue)) {child.Name} = parsedValue;");
                    }
                }
                if (child.IsCollection)
                {
                    string keysAccessor;
                    switch (child.Source)
                    {
                        case SourceKind.Query:
                            keysAccessor = "query.Keys";
                            break;
                        case SourceKind.Route:
                            keysAccessor = "route.Keys";
                            break;
                        case SourceKind.Form:
                        default:
                            keysAccessor = "form?.Keys ?? System.Array.Empty<string>()";
                            break;
                    }
                    indent.AppendLine($"var prefixCollection = {fullKeyVar} + \"[\";");
                    indent.AppendLine($"foreach (var k in {keysAccessor})");
                    indent.AppendLine("{");
                    indent.Indent();
                    indent.AppendLine("if (!k.StartsWith(prefixCollection, StringComparison.OrdinalIgnoreCase)) continue;");
                    indent.AppendLine("var idxStart = prefixCollection.Length;");
                    indent.AppendLine("var idxEnd = k.IndexOf(']', idxStart);");
                    indent.AppendLine("if (idxEnd < 0) continue;");
                    indent.AppendLine("var idxStr = k.Substring(idxStart, idxEnd - idxStart);");
                    indent.AppendLine("if (!int.TryParse(idxStr, out var index)) continue;");
                    indent.AppendLine($"while ({child.Name}.Count <= index) {{ {child.Name}.Add(default!); }}");
                    indent.AppendLine($"var elementKey = prefix + \"{child.KeyName}[\" + index + \"].\";");
                    if (!child.IsComplex)
                    {
                        var elemTypeName = GetTypeName(child.ElementType!);
                        var elemValueVar = $"elemValue_{child.Name}";
                        switch (child.Source)
                        {
                            case SourceKind.Query:
                                indent.AppendLine($"var {elemValueVar} = query[elementKey.TrimEnd('.')].Count > 0 ? query[elementKey.TrimEnd('.')].ToString() : null;");
                                break;
                            case SourceKind.Route:
                                indent.AppendLine($"var {elemValueVar} = route.TryGetValue(elementKey.TrimEnd('.'), out var tmp2_{child.Name}) ? tmp2_{child.Name}?.ToString() : null;");
                                break;
                            case SourceKind.Form:
                            default:
                                indent.AppendLine($"var {elemValueVar} = form != null && form[elementKey.TrimEnd('.')].Count > 0 ? form[elementKey.TrimEnd('.')].ToString() : null;");
                                break;
                        }
                        if (child.ElementType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.String")
                        {
                            indent.AppendLine($"{child.Name}[index] = {elemValueVar};");
                        }
                        else if (child.ElementType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Guid")
                        {
                            indent.AppendLine($"if ({elemValueVar} != null && System.Guid.TryParse({elemValueVar}, out var g)) {child.Name}[index] = g;");
                        }
                        else if (child.ElementType!.TypeKind == TypeKind.Enum)
                        {
                            var elemEnumTypeName = GetTypeName(child.ElementType!);
                            indent.AppendLine($"if ({elemValueVar} != null && System.Enum.TryParse<{elemEnumTypeName}>({elemValueVar}, true, out var e)) {child.Name}[index] = e;");
                        }
                        else
                        {
                            var elemTryParse = GetTryParseMethod(child.ElementType!);
                            indent.AppendLine($"if ({elemValueVar} != null && {elemTryParse}({elemValueVar}, out var pv)) {child.Name}[index] = pv;");
                        }
                    }
                    else
                    {
                        var elemHelper = $"Bind_{GetSanitisedTypeName(child.ElementType!)}";
                        indent.AppendLine($"{child.Name}[index] = {elemHelper}(ctx, elementKey, form, query, route);");
                    }
                    indent.Unindent();
                    indent.AppendLine("}");
                }
                indent.Unindent();
                indent.AppendLine("}");
            }
            indent.AppendLine($"var instance = new {typeName}();");
            foreach (var child in children)
            {
                indent.AppendLine($"instance.{child.Name} = {child.Name};");
            }
            indent.AppendLine("return instance;");
            indent.Unindent();
            indent.AppendLine("}");
        }
    }
}