using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HttpBinder.Generator
{
    internal static class CodeRenderer
    {
        public static string Render(BoundType model)
        {
            var buffer = new StringBuilder();

            buffer.AppendLine("// <auto-generated />");
            buffer.AppendLine("#nullable enable");
            buffer.AppendLine();

            var typeSymbol = model.TypeSymbol;
            var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
            buffer.AppendLine($"namespace {namespaceName}");
            buffer.AppendLine("{");

            var indent = new IndentedStringBuilder(buffer, 1);
            var typeKind = typeSymbol.IsRecord ? "record" : "class";

            indent.AppendLine($"partial {typeKind} {typeSymbol.Name}");
            indent.AppendLine("{");
            indent.Indent();

            RenderBindMethod(indent, model);
            RenderComplexHelpers(indent, model);

            indent.Unindent();
            indent.AppendLine("}");

            buffer.AppendLine("}");

            return buffer.ToString();
        }

        private static void RenderBindMethod(IndentedStringBuilder indent, BoundType model)
        {
            var targetTypeName = GetTypeName(model.TypeSymbol);
            var requiresForm = model.Properties.Any(p => p.Source == SourceKind.Form);

            indent.AppendLine(
                $"public static async System.Threading.Tasks.ValueTask<{targetTypeName}> BindAsync(Microsoft.AspNetCore.Http.HttpContext ctx)");
            indent.AppendLine("{");
            indent.Indent();

            if (requiresForm)
                indent.AppendLine("var form = await ctx.Request.ReadFormAsync().ConfigureAwait(false);");

            indent.AppendLine("var query = ctx.Request.Query;");
            indent.AppendLine("var route = ctx.Request.RouteValues;");
            indent.AppendLine();

            foreach (var property in model.Properties)
                GeneratePropertyBinding(indent, property, requiresForm);

            indent.AppendLine();

            if (model.Constructor is not null && model.Constructor.Parameters.Length > 0)
            {
                RenderConstructorBasedInitialization(indent, model, targetTypeName);
            }
            else
            {
                RenderPropertyAssignmentInitialization(indent, model, targetTypeName);
            }

            indent.Unindent();
            indent.AppendLine("}");
        }

        private static void RenderConstructorBasedInitialization(
            IndentedStringBuilder indent,
            BoundType model,
            string targetTypeName)
        {
            indent.AppendLine($"var result = new {targetTypeName}(");
            indent.Indent();

            for (int i = 0; i < model.Constructor!.Parameters.Length; i++)
            {
                var (_, mappedProperty) = model.ConstructorMapping[i];
                var trailing = (i == model.Constructor.Parameters.Length - 1) ? "" : ",";
                indent.AppendLine($"{mappedProperty.Name}{trailing}");
            }

            indent.Unindent();
            indent.AppendLine(");");

            var remainingProps = model.Properties
                .Where(p => !model.ConstructorMapping.Any(m => m.property == p));

            foreach (var prop in remainingProps)
                indent.AppendLine($"result.{prop.Name} = {prop.Name};");

            indent.AppendLine("return result;");
        }

        private static void RenderPropertyAssignmentInitialization(
            IndentedStringBuilder indent,
            BoundType model,
            string targetTypeName)
        {
            indent.AppendLine($"var result = new {targetTypeName}();");

            foreach (var property in model.Properties)
                indent.AppendLine($"result.{property.Name} = {property.Name};");

            indent.AppendLine("return result;");
        }

        private static void GeneratePropertyBinding(
            IndentedStringBuilder indent,
            BoundProperty property,
            bool requiresForm)
        {
            var localName = property.Name;
            var typeName = GetTypeName(property.Symbol.Type);

            EmitPropertyDeclaration(indent, localName, typeName, property);

            indent.AppendLine("{");
            indent.Indent();

            if (property.IsCollection)
            {
                GenerateCollectionBinding(indent, property, requiresForm);
                ClosePropertyScope(indent);
                return;
            }

            if (property.IsComplex)
            {
                var helper = $"Bind_{GetSanitisedTypeName(property.Symbol.Type)}";
                var formArg = requiresForm ? "form" : "null";
                indent.AppendLine(
                    $"{localName} = {helper}(ctx, \"{property.KeyName}.\", {formArg}, query, route);");
                ClosePropertyScope(indent);
                return;
            }

            GenerateSimplePropertyValueBinding(indent, property, localName, requiresForm);

            ClosePropertyScope(indent);
        }

        private static void EmitPropertyDeclaration(
            IndentedStringBuilder indent,
            string localName,
            string typeName,
            BoundProperty prop)
        {
            if (prop.IsCollection)
            {
                indent.AppendLine($"{typeName} {localName} = new {typeName}();");
                return;
            }

            var initializer = (prop.IsNullable || prop.Symbol.Type.IsReferenceType)
                ? "default!"
                : "default";

            indent.AppendLine($"{typeName} {localName} = {initializer};");
        }

        private static void ClosePropertyScope(IndentedStringBuilder indent)
        {
            indent.Unindent();
            indent.AppendLine("}");
        }

        private static void GenerateSimplePropertyValueBinding(
            IndentedStringBuilder indent,
            BoundProperty property,
            string localName,
            bool requiresForm)
        {
            var valueVar = $"value_{localName}";

            EmitValueAccessor(indent, property, valueVar, requiresForm);
            EmitValueParser(indent, property, localName, valueVar);
        }

        private static void EmitValueAccessor(
            IndentedStringBuilder indent,
            BoundProperty prop,
            string valueVar,
            bool requiresForm)
        {
            string key = prop.KeyName;

            switch (prop.Source)
            {
                case SourceKind.Query:
                    indent.AppendLine(
                        $"var {valueVar} = query[\"{key}\"].Count > 0 ? query[\"{key}\"].ToString() : null;");
                    break;

                case SourceKind.Route:
                    indent.AppendLine(
                        $"var {valueVar} = route.TryGetValue(\"{key}\", out var tmp) ? tmp?.ToString() : null;");
                    break;

                case SourceKind.Form:
                default:
                    if (requiresForm)
                        indent.AppendLine(
                            $"var {valueVar} = form[\"{key}\"].Count > 0 ? form[\"{key}\"].ToString() : null;");
                    else
                        indent.AppendLine(
                            $"var {valueVar} = ctx.Request.Form[\"{key}\"].Count > 0 ? ctx.Request.Form[\"{key}\"].ToString() : null;");
                    break;
            }
        }

        private static void EmitValueParser(
            IndentedStringBuilder indent,
            BoundProperty prop,
            string localName,
            string valueVar)
        {
            if (prop.IsString)
            {
                indent.AppendLine($"{localName} = {valueVar};");
                return;
            }

            if (prop.IsGuid)
            {
                indent.AppendLine(
                    $"if ({valueVar} != null && System.Guid.TryParse({valueVar}, out var g)) {localName} = g;");
                return;
            }

            if (prop.IsEnum)
            {
                var enumName = GetTypeName(prop.Symbol.Type);
                indent.AppendLine(
                    $"if ({valueVar} != null && System.Enum.TryParse<{enumName}>({valueVar}, true, out var e)) {localName} = e;");
                return;
            }

            if (prop.IsPrimitive)
            {
                var tryParse = GetTryParseMethod(prop.Symbol.Type);
                indent.AppendLine(
                    $"if ({valueVar} != null && {tryParse}({valueVar}, out var pv)) {localName} = pv;");
                return;
            }

            indent.AppendLine($"// unsupported type: {GetTypeName(prop.Symbol.Type)}");
        }

        private static void GenerateCollectionBinding(
            IndentedStringBuilder indent,
            BoundProperty property,
            bool requiresForm)
        {
            var listName = property.Name;
            var elementType = property.ElementType!;
            var collectionKey = property.KeyName;

            var keysSource = property.Source switch
            {
                SourceKind.Query => "query.Keys",
                SourceKind.Route => "route.Keys",
                _ => requiresForm ? "form.Keys" : "ctx.Request.Form.Keys",
            };

            indent.AppendLine($"var itemPrefix = \"{collectionKey}[\";");

            indent.AppendLine($"foreach (var key in {keysSource})");
            indent.AppendLine("{");
            indent.Indent();

            indent.AppendLine("if (!key.StartsWith(itemPrefix, StringComparison.OrdinalIgnoreCase)) continue;");
            indent.AppendLine("var start = itemPrefix.Length;");
            indent.AppendLine("var end = key.IndexOf(']', start);");
            indent.AppendLine("if (end < 0) continue;");

            indent.AppendLine("var idxStr = key.Substring(start, end - start);");
            indent.AppendLine("if (!int.TryParse(idxStr, out var index)) continue;");

            indent.AppendLine($"while ({listName}.Count <= index) {{ {listName}.Add(default!); }}");
            indent.AppendLine($"var elementPrefix = \"{collectionKey}[\" + index + \"].\";");

            if (property.IsComplex)
            {
                var helper = $"Bind_{GetSanitisedTypeName(elementType)}";
                var formArg = requiresForm ? "form" : "null";
                indent.AppendLine($"{listName}[index] = {helper}(ctx, elementPrefix, {formArg}, query, route);");
                indent.Unindent();
                indent.AppendLine("}");
                return;
            }

            EmitSimpleCollectionElementBinding(indent, property, listName, elementType);

            indent.Unindent();
            indent.AppendLine("}");
        }

        private static void EmitSimpleCollectionElementBinding(
            IndentedStringBuilder indent,
            BoundProperty property,
            string listName,
            ITypeSymbol elemType)
        {
            var elemValueVar = $"elemValue_{listName}";

            string accessor = property.Source switch
            {
                SourceKind.Query => "query",
                SourceKind.Route => "route",
                SourceKind.Form => "form",
                _ => "form"
            };

            indent.AppendLine($"var {elemValueVar} = {accessor}[elementPrefix.TrimEnd('.')].Count > 0 ? {accessor}[elementPrefix.TrimEnd('.')].ToString() : null;");

            var typeName = elemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (typeName == "global::System.String")
            {
                indent.AppendLine($"{listName}[index] = {elemValueVar};");
                return;
            }

            if (typeName == "global::System.Guid")
            {
                indent.AppendLine(
                    $"if ({elemValueVar} != null && System.Guid.TryParse({elemValueVar}, out var g)) {listName}[index] = g;");
                return;
            }

            if (elemType.TypeKind == TypeKind.Enum)
            {
                var enumType = GetTypeName(elemType);
                indent.AppendLine(
                    $"if ({elemValueVar} != null && System.Enum.TryParse<{enumType}>({elemValueVar}, true, out var e)) {listName}[index] = e;");
                return;
            }

            var tryParse = GetTryParseMethod(elemType);
            indent.AppendLine(
                $"if ({elemValueVar} != null && {tryParse}({elemValueVar}, out var pv)) {listName}[index] = pv;");
        }

        private static void RenderComplexHelpers(IndentedStringBuilder indent, BoundType model)
        {
            var emitted = new HashSet<string>(StringComparer.Ordinal);

            void Process(BoundProperty prop)
            {
                if (prop.IsComplex)
                {
                    var sanitized = GetSanitisedTypeName(prop.Symbol.Type);

                    if (!emitted.Contains(sanitized))
                    {
                        emitted.Add(sanitized);
                        RenderComplexHelper(indent, prop.Symbol.Type, prop.Children);
                    }

                    foreach (var child in prop.Children)
                        Process(child);
                }

                if (prop.IsCollection && prop.ElementType is ITypeSymbol elem)
                {
                    if (NeedsComplexHelper(elem))
                    {
                        var sanitized = GetSanitisedTypeName(elem);

                        if (!emitted.Contains(sanitized))
                        {
                            emitted.Add(sanitized);
                            RenderComplexHelper(indent, elem, prop.Children);
                        }
                    }
                }
            }

            foreach (var p in model.Properties)
                Process(p);
        }

        private static bool NeedsComplexHelper(ITypeSymbol type)
        {
            if (type.SpecialType == SpecialType.System_String)
                return false;

            if (type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Guid")
                return false;

            if (type is INamedTypeSymbol nts && nts.TypeKind == TypeKind.Enum)
                return false;

            if (type is INamedTypeSymbol n1 && n1.SpecialType != SpecialType.None)
                return false;

            return true;
        }

        private static void RenderComplexHelper(
            IndentedStringBuilder indent,
            ITypeSymbol typeSymbol,
            List<BoundProperty> children)
        {
            var typeName = GetTypeName(typeSymbol);
            var helperName = $"Bind_{GetSanitisedTypeName(typeSymbol)}";

            indent.AppendLine(
                $"private static {typeName} {helperName}(Microsoft.AspNetCore.Http.HttpContext ctx, string prefix, Microsoft.AspNetCore.Http.IFormCollection? form, Microsoft.AspNetCore.Http.IQueryCollection query, Microsoft.AspNetCore.Routing.RouteValueDictionary route)");
            indent.AppendLine("{");
            indent.Indent();

            EmitChildDeclarations(indent, children);
            EmitChildBindings(indent, children);

            indent.AppendLine($"var instance = new {typeName}();");

            foreach (var child in children)
                indent.AppendLine($"instance.{child.Name} = {child.Name};");

            indent.AppendLine("return instance;");

            indent.Unindent();
            indent.AppendLine("}");
        }

        private static void EmitChildDeclarations(IndentedStringBuilder indent, List<BoundProperty> children)
        {
            foreach (var child in children)
            {
                var childType = GetTypeName(child.Symbol.Type);

                if (child.IsCollection)
                {
                    indent.AppendLine($"{childType} {child.Name} = new {childType}();");
                    continue;
                }

                var initializer = (child.IsNullable || child.Symbol.Type.IsReferenceType)
                    ? "default!"
                    : "default";

                indent.AppendLine($"{childType} {child.Name} = {initializer};");
            }
        }

        private static void EmitChildBindings(IndentedStringBuilder indent, List<BoundProperty> children)
        {
            foreach (var child in children)
            {
                indent.AppendLine("{");
                indent.Indent();

                var fullKey = $"prefix + \"{child.KeyName}\"";
                var keyVar = $"key_{child.Name}";

                indent.AppendLine($"var {keyVar} = {fullKey};");

                if (!child.IsCollection)
                {
                    EmitComplexChildValueBinding(indent, child, keyVar);
                }
                else
                {
                    EmitComplexChildCollectionBinding(indent, child, keyVar);
                }

                indent.Unindent();
                indent.AppendLine("}");
            }
        }

        private static void EmitComplexChildValueBinding(
            IndentedStringBuilder indent,
            BoundProperty child,
            string keyVar)
        {
            var valueVar = $"value_{child.Name}";

            string accessor = child.Source switch
            {
                SourceKind.Query => $"query[{keyVar}]",
                SourceKind.Route => $"route.TryGetValue({keyVar}, out var tmp) ? tmp?.ToString() : null",
                SourceKind.Form => $"form != null && form[{keyVar}].Count > 0 ? form[{keyVar}].ToString() : null",
                _ => $"form != null && form[{keyVar}].Count > 0 ? form[{keyVar}].ToString() : null",
            };

            if (child.Source == SourceKind.Route)
                indent.AppendLine($"var {valueVar} = {accessor};");
            else
                indent.AppendLine($"var {valueVar} = {accessor}.Count > 0 ? {accessor}.ToString() : null;");

            if (child.IsComplex)
            {
                var nested = $"Bind_{GetSanitisedTypeName(child.Symbol.Type)}";
                indent.AppendLine(
                    $"{child.Name} = {nested}(ctx, {keyVar} + \".\", form, query, route);");
                return;
            }

            EmitValueParser(indent, child, child.Name, valueVar);
        }

        private static void EmitComplexChildCollectionBinding(
            IndentedStringBuilder indent,
            BoundProperty child,
            string keyVar)
        {
            string keysSource = child.Source switch
            {
                SourceKind.Query => "query.Keys",
                SourceKind.Route => "route.Keys",
                SourceKind.Form => "form?.Keys ?? System.Array.Empty<string>()",
                _ => "form?.Keys ?? System.Array.Empty<string>()"
            };

            indent.AppendLine($"var collectionPrefix = {keyVar} + \"[\";");

            indent.AppendLine($"foreach (var k in {keysSource})");
            indent.AppendLine("{");
            indent.Indent();

            indent.AppendLine("if (!k.StartsWith(collectionPrefix, StringComparison.OrdinalIgnoreCase)) continue;");
            indent.AppendLine("var start = collectionPrefix.Length;");
            indent.AppendLine("var end = k.IndexOf(']', start);");
            indent.AppendLine("if (end < 0) continue;");
            indent.AppendLine("var idxStr = k.Substring(start, end - start);");
            indent.AppendLine("if (!int.TryParse(idxStr, out var index)) continue;");

            indent.AppendLine($"while ({child.Name}.Count <= index) {{ {child.Name}.Add(default!); }}");

            indent.AppendLine($"var elementKey = prefix + \"{child.KeyName}[\" + index + \"].\";");

            if (child.IsComplex)
            {
                var elemHelper = $"Bind_{GetSanitisedTypeName(child.ElementType!)}";
                indent.AppendLine(
                    $"{child.Name}[index] = {elemHelper}(ctx, elementKey, form, query, route);");
            }
            else
            {
                EmitSimpleCollectionElementBinding(indent, child, child.Name, child.ElementType!);
            }

            indent.Unindent();
            indent.AppendLine("}");
        }

        private static string GetTypeName(ITypeSymbol typeSymbol)
            => typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        private static string GetSanitisedTypeName(ITypeSymbol symbol)
        {
            var raw = symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            var buffer = new StringBuilder(raw.Length);

            foreach (var ch in raw)
                buffer.Append(char.IsLetterOrDigit(ch) ? ch : '_');

            return buffer.ToString();
        }

        private static string GetTryParseMethod(ITypeSymbol type)
        {
            var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            return full switch
            {
                "global::System.Boolean" => "bool.TryParse",
                "global::System.Byte" => "byte.TryParse",
                "global::System.SByte" => "sbyte.TryParse",
                "global::System.Int16" => "short.TryParse",
                "global::System.UInt16" => "ushort.TryParse",
                "global::System.Int32" => "int.TryParse",
                "global::System.UInt32" => "uint.TryParse",
                "global::System.Int64" => "long.TryParse",
                "global::System.UInt64" => "ulong.TryParse",
                "global::System.Single" => "float.TryParse",
                "global::System.Double" => "double.TryParse",
                "global::System.Decimal" => "decimal.TryParse",
                _ => "int.TryParse"
            };
        }
    }
}
