using Blueprint.HttpBinder.Extensions;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Blueprint.HttpBinder;

/// <summary>
/// Emits the generated binder source for a DTO bound via BindAsync().
/// The renderer prioritizes human readability and is completely symbol-free.
/// </summary>
internal static class CodeRenderer
{
    public static string Render(BoundType model)
    {
        var stringBuilder = new StringBuilder();

        stringBuilder.AppendLine("// <auto-generated />");
        stringBuilder.AppendLine("#nullable enable");
        stringBuilder.AppendLine();

        // Common not to have a namespace in single-file programs.
        var hasNamespace = !string.IsNullOrWhiteSpace(model.Namespace);
        if (hasNamespace)
        {
            stringBuilder.AppendLine($"namespace {model.Namespace}");
            stringBuilder.AppendLine("{");
        }

        var indent = new IndentedStringBuilder(stringBuilder, 1);

        var typeDeclaration = model.Kind switch
        {
            BoundTypeKind.Class => "class",
            BoundTypeKind.RecordClass => "record",
            _ => "class"
        };

        indent.AppendLine($"partial {typeDeclaration} {model.Name}");
        indent.AppendLine("{");
        indent.Indent();

        RenderBindMethod(indent, model);
        RenderComplexHelpers(indent, model);

        indent.Unindent();
        indent.AppendLine("}");

        if (hasNamespace)
            stringBuilder.AppendLine("}");

        return stringBuilder.ToString();
    }

    private static void RenderBindMethod(IndentedStringBuilder indent, BoundType model)
    {
        var typeName = model.FullName;
        var usesForm = model.UsesFormValues();
        var usesQuery = model.UsesQueryValues();
        var usesRoute = model.UsesRouteValues();

        indent.AppendLine($"public static async global::System.Threading.Tasks.ValueTask<{typeName}> BindAsync(");
        indent.AppendLine("    global::Microsoft.AspNetCore.Http.HttpContext http)");
        indent.AppendLine("{");
        indent.Indent();

        indent.AppendLine("var request = http.Request;");

        if (usesForm)
            indent.AppendLine("var form = await request.ReadFormAsync().ConfigureAwait(false);");

        if (usesQuery)
            indent.AppendLine("var query = request.Query;");

        if (usesRoute)
            indent.AppendLine("var route = request.RouteValues;");

        indent.AppendLine();

        // 1. Generate locals for each property
        foreach (var property in model.Properties)
        {
            GeneratePropertyBinding(indent, property);
            indent.AppendLine();
        }

        // Determine which properties must go into object initializer.
        var initOrSettableProperties = new EquatableArray<BoundProperty>(
            [.. model.Properties.Where(p => !p.IsConstructorParameter)]);

        var ctorArgs = string.Join(", ", model.ConstructorParameterNames.Select(name => $"{name}: {BoundProperty.ToCamelCase(name)}"));

        indent.AppendLine($"var instance = new {typeName}({ctorArgs})");
        indent.AppendLine("{");
        indent.Indent();

        GeneratePropertyAssigments(indent, initOrSettableProperties);

        indent.Unindent();
        indent.AppendLine("};");

        indent.AppendLine();
        indent.AppendLine("return instance;");
        indent.Unindent();
        indent.AppendLine("}");
    }

    private static void GeneratePropertyAssigments(IndentedStringBuilder indent, EquatableArray<BoundProperty> properties)
    {
        foreach (var property in properties)
        {
            // Collections inside initializer must use assignment expression
            if (property.IsCollection && !property.IsFormFile)
            {
                var local = property.CamelCaseName;
                var assignmentExpr = GetCollectionAssignmentExpression(property, local);
                indent.AppendLine($"{property.Name} = {assignmentExpr},");
            }
            else
            {
                indent.AppendLine($"{property.Name} = {property.CamelCaseName},");
            }
        }
    }

    private static void GeneratePropertyBinding(
        IndentedStringBuilder indent,
        BoundProperty property)
    {
        EmitLocalDeclaration(indent, property);

        if (property.IsFormFile)
        {
            if (property.HttpBinderType == HttpBinderType.Form)
            {
                EmitFormFileBinding(indent, property);
            }

            // else: unsupported combination; leave as default/null
            return;
        }

        if (property.IsCollection)
        {
            GenerateCollectionBinding(indent, property);
            return;
        }

        if (property.IsReferenceType)
        {
            if (property.HttpBinderType == HttpBinderType.Form)
            {
                EmitComplexCall(indent, property);
            }

            // Query/Route complex binding is not supported; leave default
            return;
        }

        // Simple scalar value
        EmitSimpleBinding(indent, property);
    }

    private static void EmitLocalDeclaration(
        IndentedStringBuilder indent,
        BoundProperty property)
    {
        // Root IFormFileCollection / List<IFormFile> – we let the binding logic assign.
        if (property.IsFormFile && property.IsCollection)
        {
            indent.AppendLine($"{property.DeclaredTypeName} {property.CamelCaseName} = null!;");
            return;
        }

        // Collections (we always back them by List<T> locals for non-file types)
        if (property.IsCollection)
        {
            var listType = $"global::System.Collections.Generic.List<{property.TypeName}>";
            indent.AppendLine($"{listType} {property.CamelCaseName} = new {listType}();");
            return;
        }

        // Scalar IFormFile
        if (property.IsFormFile)
        {
            indent.AppendLine($"{property.TypeName} {property.CamelCaseName} = null!;");
            return;
        }

        // Complex scalar
        if (property.IsReferenceType && !property.IsNullable)
        {
            indent.AppendLine($"{property.TypeName} {property.CamelCaseName} = null!;");
            return;
        }

        // Nullable or string scalar
        if (property.IsNullable || property.IsString)
        {
            indent.AppendLine($"{property.TypeName} {property.CamelCaseName} = null!;");
            return;
        }

        // Non-nullable primitive / enum
        indent.AppendLine($"{property.TypeName} {property.CamelCaseName} = default;");
    }

    private static void EmitFormFileBinding(IndentedStringBuilder indent, BoundProperty property)
    {
        var key = property.KeyName;

        // user declared "IFormFileCollection"
        if (property.DeclaredTypeName == "Microsoft.AspNetCore.Http.IFormFileCollection")
        {
            indent.AppendLine(
                $"var {property.CamelCaseName}FileList = http.Request.Form.Files.GetFiles(\"{key}\");");
            indent.AppendLine($"var {property.CamelCaseName}FileCollection = new FormFileCollection();");
            indent.AppendLine($"foreach (var file in {property.CamelCaseName}FileList) {property.CamelCaseName}FileCollection.Add(file);");
            indent.AppendLine($"{property.CamelCaseName} = {property.CamelCaseName}FileCollection;");
            return;
        }

        // Otherwise treat as a collection of IFormFile (List<IFormFile>)
        if (property.IsCollection)
        {
            indent.AppendLine(
                $"{property.CamelCaseName} = new global::System.Collections.Generic.List<Microsoft.AspNetCore.Http.IFormFile>(http.Request.Form.Files.GetFiles(\"{key}\"));");
            return;
        }

        // Scalar IFormFile
        indent.AppendLine($"{property.CamelCaseName} = http.Request.Form.Files.GetFile(\"{key}\");");
    }

    private static void EmitSimpleBinding(
        IndentedStringBuilder indent,
        BoundProperty property)
    {
        var rawVar = $"{property.CamelCaseName}Raw";
        EmitValueAccessor(indent, property, rawVar);
        EmitValueParser(indent, property, property.CamelCaseName, rawVar, false);
    }

    private static void EmitValueAccessor(
        IndentedStringBuilder indent,
        BoundProperty property,
        string rawVar)
    {
        var key = property.KeyName;
        var local = property.CamelCaseName;

        switch (property.HttpBinderType)
        {
            case HttpBinderType.Query:
                indent.AppendLine(
                    $"var {rawVar} = query.TryGetValue(\"{key}\", out var {local}QueryValue) && {local}QueryValue.Count > 0 ? {local}QueryValue.ToString() : null;");
                break;

            case HttpBinderType.Route:
                indent.AppendLine(
                    $"var {rawVar} = route.TryGetValue(\"{key}\", out var {local}RouteValue) ? {local}RouteValue?.ToString() : null;");
                break;
            case HttpBinderType.Form:
            default:
                indent.AppendLine(
                    $"var {rawVar} = form.TryGetValue(\"{key}\", out var {local}FormValue) && {local}FormValue.Count > 0 ? {local}FormValue.ToString() : null;");
                break;
        }
    }

    private static void EmitValueParser(
        IndentedStringBuilder indent,
        BoundProperty property,
        string assignmentTarget,
        string rawVar,
        bool useAdd)
    {
        var parsed = $"{assignmentTarget.Replace(".", "")}Parsed";

        string assign =
            useAdd
            ? $"{assignmentTarget}.Add("      // e.g. myList.Add(
            : $"{assignmentTarget} = ";   // e.g. age =

        // End paren for collection adds
        string closing = useAdd ? ");" : ";";

        if (property.IsString)
        {
            indent.AppendLine($"if (!string.IsNullOrEmpty({rawVar})) {assign}{rawVar}{closing}");
        }
        else if (property.IsEnum)
        {
            indent.AppendLine(
                $"if ({rawVar} != null && Enum.TryParse<{property.NonNullTypeName}>({rawVar}, true, out var {parsed})) {assign}{parsed}{closing}");
        }
        else
        {
            indent.AppendLine(
                $"if ({rawVar} != null && {property.GetTryParseMethod()}({rawVar}, out var {parsed})) {assign}{parsed}{closing}");
        }
    }

    private static void EmitComplexCall(
        IndentedStringBuilder indent,
        BoundProperty property)
    {
        // Only used for HttpBinderType.Form
        var helper = $"Bind_{Sanitize(property.TypeName)}";
        indent.AppendLine($"{property.CamelCaseName} = {helper}(http, \"{property.KeyName}.\", form);");
    }

    private static void GenerateCollectionBinding(
        IndentedStringBuilder indent,
        BoundProperty property)
    {
        if (property.HttpBinderType == HttpBinderType.Route)
        {
            indent.AppendLine($"// Collections cannot be bound from route values.");
            return;
        }

        if (property.IsReferenceType)
        {
            if (property.HttpBinderType != HttpBinderType.Form)
            {
                indent.AppendLine("// Complex collections can only be bound from form values.");
                return;
            }

            EmitRootComplexCollection(indent, property);
            return;
        }

        var keyName = property.KeyName;

        if (property.HttpBinderType == HttpBinderType.Query)
        {
            indent.AppendLine($"if (query.TryGetValue(\"{keyName}\", out var {keyName}Values))");
        }
        else
        {
            indent.AppendLine($"if (form.TryGetValue(\"{keyName}\", out var {keyName}Values))");
        }

        var rawVar = "val";
        indent.AppendLine("{");
        indent.Indent();
        indent.AppendLine($"foreach (var {rawVar} in {keyName}Values)");
        indent.AppendLine("{");
        indent.Indent();

        EmitValueParser(indent, property, property.CamelCaseName, rawVar, useAdd: true);

        indent.Unindent();
        indent.AppendLine("}");
        indent.Unindent();
        indent.AppendLine("}");
    }

    private static void RenderComplexHelpers(IndentedStringBuilder indent, BoundType model)
    {
        var emitted = new HashSet<string>();

        foreach (var p in model.Properties)
            Walk(p);

        void Walk(BoundProperty property)
        {
            if (property.IsFormFile)
                return;

            if (property.IsReferenceType && emitted.Add(property.TypeName))
                RenderComplexHelper(indent, property.TypeName, property.ChildProperties);

            foreach (var childProperty in property.ChildProperties)
                Walk(childProperty);
        }
    }

    private static void RenderComplexHelper(
        IndentedStringBuilder indent,
        string typeName,
        EquatableArray<BoundProperty> properties)
    {
        var helper = $"Bind_{Sanitize(typeName)}";

        indent.AppendLine($"private static {typeName} {helper}(");
        indent.AppendLine("    global::Microsoft.AspNetCore.Http.HttpContext http,");
        indent.AppendLine("    string prefix,");
        indent.AppendLine("    global::Microsoft.AspNetCore.Http.IFormCollection? form)");
        indent.AppendLine("{");
        indent.Indent();

        // Locals
        foreach (var property in properties)
        {
            if (property.IsCollection && !property.IsFormFile)
            {
                var listType = $"global::System.Collections.Generic.List<{property.TypeName}>";
                indent.AppendLine($"{listType} {property.CamelCaseName} = new {listType}();");
            }
            else if (property.IsNullable || property.IsString || property.IsFormFile)
            {
                indent.AppendLine($"{property.TypeName} {property.CamelCaseName} = null!;");
            }
            else
            {
                indent.AppendLine($"{property.TypeName} {property.CamelCaseName} = default;");
            }
        }

        indent.AppendLine();

        // Binding logic for each child property (form-only)
        foreach (var property in properties)
        {
            var local = property.CamelCaseName;
            var keyVar = $"{local}Key";
            indent.AppendLine($"var {keyVar} = prefix + \"{property.KeyName}\";");

            if (property.IsFormFile)
            {
                // We do not attempt to support IFormFile inside complex types today; leave default.
                indent.AppendLine($"// File uploads inside complex types are not bound automatically. '{property.Name}' remains at its default value.");
            }
            else if (property.IsCollection)
            {
                EmitComplexChildCollection(indent, property, local, keyVar);
            }
            else if (property.IsReferenceType)
            {
                var nested = $"Bind_{Sanitize(property.TypeName)}";
                indent.AppendLine($"{local} = {nested}(http, {keyVar} + \".\", form);");
            }
            else
            {
                EmitComplexChildSimple(indent, property, local, keyVar);
            }

            indent.AppendLine();
        }

        indent.AppendLine($"var instance = new {typeName}");
        indent.AppendLine("{");
        indent.Indent();

        GeneratePropertyAssigments(indent, properties);

        indent.Unindent();
        indent.AppendLine("};");
        indent.AppendLine("return instance;");

        indent.Unindent();
        indent.AppendLine("}");
    }

    private static void EmitComplexChildSimple(
        IndentedStringBuilder indent,
        BoundProperty property,
        string local,
        string keyVar)
    {
        var raw = $"{local}Raw";
        indent.AppendLine($"var {raw} = form != null && form.TryGetValue({keyVar}, out var {local}Temp) && {local}Temp.Count > 0 ? {local}Temp.ToString() : null;");
        EmitValueParser(indent, property, local, raw, false);
    }

    private static void EmitComplexChildCollection(
        IndentedStringBuilder indent,
        BoundProperty property,
        string local,
        string keyVar)
    {
        // Complex collections inside complex types are always form-based
        var prefixVar = $"{local}Prefix";
        indent.AppendLine($"var {prefixVar} = {keyVar} + \"[\";");

        indent.AppendLine("foreach (var key in form?.Keys ?? global::System.Array.Empty<string>())");
        indent.AppendLine("{");
        indent.Indent();

        indent.AppendLine($"if (!key.StartsWith({prefixVar})) continue;");
        indent.AppendLine($"var idxStart = {prefixVar}.Length;");
        indent.AppendLine("var idxEnd = key.IndexOf(']', idxStart);");
        indent.AppendLine("if (idxEnd < 0) continue;");
        indent.AppendLine("var idxText = key.Substring(idxStart, idxEnd - idxStart);");
        indent.AppendLine("if (!int.TryParse(idxText, out var index)) continue;");
        indent.AppendLine($"while ({local}.Count <= index) {local}.Add(default);");

        if (property.IsReferenceType)
        {
            var nested = $"Bind_{Sanitize(property.TypeName)}";
            indent.AppendLine($"{local}[index] = {nested}(http, key + \".\", form);");
        }
        else
        {
            var raw = $"{local}ElementRaw";
            indent.AppendLine($"string? {raw} = null;");
            indent.AppendLine("if (form != null && form.TryGetValue(key, out var formValue) && formValue.Count > 0) " +
                              $"{raw} = formValue.ToString();");

            EmitValueParser(indent, property, $"{local}[index]", raw, false);
        }

        indent.Unindent();
        indent.AppendLine("}");
    }

    private static void EmitRootComplexCollection(
     IndentedStringBuilder indent,
     BoundProperty property)
    {
        var keyName = property.KeyName;
        var prefixVar = $"{property.CamelCaseName}Prefix";

        // Prefix looks like: "NestedClassList["
        indent.AppendLine($"var {prefixVar} = \"{keyName}[\";");

        indent.AppendLine("foreach (var key in form.Keys)");
        indent.AppendLine("{");
        indent.Indent();

        indent.AppendLine($"if (!key.StartsWith({prefixVar})) continue;");

        indent.AppendLine($"var idxStart = {prefixVar}.Length;");
        indent.AppendLine("var idxEnd = key.IndexOf(']', idxStart);");
        indent.AppendLine("if (idxEnd < 0) continue;");

        indent.AppendLine("var idxText = key.Substring(idxStart, idxEnd - idxStart);");
        indent.AppendLine("if (!int.TryParse(idxText, out var index)) continue;");

        // Ensure capacity
        indent.AppendLine($"while ({property.CamelCaseName}.Count <= index) {property.CamelCaseName}.Add(default!);");

        // Extract correct prefix *including trailing dot*:
        // "NestedClassList[0]."
        indent.AppendLine("var objPrefix = key.Substring(0, idxEnd + 1) + \".\";");

        var nested = $"Bind_{Sanitize(property.TypeName)}";

        // Bind the complex object using the correct prefix
        indent.AppendLine($"{property.CamelCaseName}[index] = {nested}(http, objPrefix, form);");

        indent.Unindent();
        indent.AppendLine("}");
    }

    private static string GetCollectionAssignmentExpression(BoundProperty property, string local)
    {
        // We only apply this for non-formfile collections (where locals are List<T>)
        var declared = property.DeclaredTypeName;

        // Arrays: T[] => ToArray(List<T>)
        if (declared.EndsWith("[]"))
        {
            return $"global::System.Linq.Enumerable.ToArray({local})";
        }

        // Normalize in case the declared type has global:: prefix
        if (declared.StartsWith("global::"))
            declared = declared.Substring("global::".Length);

        // List<T> – List<T> already
        if (declared.StartsWith("System.Collections.Generic.List<"))
        {
            return local;
        }

        // IEnumerable<T>, ICollection<T> – List<T> implements these directly
        if (declared.StartsWith("System.Collections.Generic.IEnumerable<") ||
            declared.StartsWith("System.Collections.Generic.ICollection<"))
        {
            return local;
        }

        // IReadOnlyCollection<T>, IReadOnlyList<T> – use ToArray as a simple, safe representation
        if (declared.StartsWith("System.Collections.Generic.IReadOnlyCollection<") ||
            declared.StartsWith("System.Collections.Generic.IReadOnlyList<"))
        {
            return $"global::System.Linq.Enumerable.ToArray({local})";
        }

        // Fallback: assign List<T> as-is; if this is incompatible the compiler will tell the user.
        return local;
    }

    private static string Sanitize(string fullTypeName)
    {
        var sb = new StringBuilder(fullTypeName.Length);
        foreach (var c in fullTypeName)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }
}
