using Blueprint.HttpBinder.Extensions;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Blueprint.HttpBinder;

/// <summary>
/// Emits the generated binder source for a DTO bound via BindAsync().
/// The renderer prioritizes human readability and is completely symbol-free.
/// </summary>
internal static class CodeRenderer
{
    public static string Render(BoundType model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");

        var indent = new IndentedStringBuilder(sb, 1);

        indent.AppendLine($"partial class {model.Name}");
        indent.AppendLine("{");
        indent.Indent();

        RenderBindMethod(indent, model);
        indent.AppendLine();
        RenderComplexHelpers(indent, model);

        indent.Unindent();
        indent.AppendLine("}");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void RenderBindMethod(IndentedStringBuilder indent, BoundType model)
    {
        var typeName = model.FullName;
        var usesForm = UsesForm(model);
        var usesQuery = UsesQueryAtRoot(model);
        var usesRoute = UsesRouteAtRoot(model);

        indent.AppendLine($"public static async global::System.Threading.Tasks.ValueTask<{typeName}> BindAsync(");
        indent.AppendLine("    global::Microsoft.AspNetCore.Http.HttpContext http)");
        indent.AppendLine("{");
        indent.Indent();

        indent.AppendLine("var request = http.Request;");

        if (usesForm)
            indent.AppendLine("var form = await request.ReadFormAsync().ConfigureAwait(false);");

        if (usesQuery)
            indent.AppendLine("var query = request.Query;");

        if (usesRoute)
            indent.AppendLine("var route = request.RouteValues;");

        indent.AppendLine();

        foreach (var property in model.Properties)
        {
            if (property.IsIgnored) continue;

            GeneratePropertyBinding(indent, property, usesForm);
            indent.AppendLine();
        }

        indent.AppendLine($"var instance = new {typeName}();");

        foreach (var p in model.Properties)
        {
            if (p.IsIgnored) continue;
            indent.AppendLine($"instance.{p.Name} = {ToCamelCase(p.Name)};");
        }

        indent.AppendLine("return instance;");
        indent.Unindent();
        indent.AppendLine("}");
    }

    private static bool UsesForm(BoundType model) =>
        model.Properties.Any(UsesFormRecursive);

    private static bool UsesFormRecursive(BoundProperty property)
    {
        if (property.HttpBinderType == HttpBinderType.Form)
            return true;

        foreach (var childProperty in property.ChildProperties)
            if (UsesFormRecursive(childProperty))
                return true;

        return false;
    }

    private static bool UsesQueryAtRoot(BoundType model) =>
        model.Properties.Any(p => p.HttpBinderType == HttpBinderType.Query);

    private static bool UsesRouteAtRoot(BoundType model) =>
        model.Properties.Any(p => p.HttpBinderType == HttpBinderType.Route);

    private static void GeneratePropertyBinding(
        IndentedStringBuilder indent,
        BoundProperty property,
        bool usesForm)
    {
        var name = property.Name;
        var local = ToCamelCase(name);
        var elementType = property.TypeName;

        EmitLocalDeclaration(indent, property, local, elementType);

        if (property.IsCollection)
        {
            GenerateCollectionBinding(indent, property, local, usesForm);
            return;
        }

        if (property.IsComplex)
        {
            EmitComplexCall(indent, property, local, usesForm);
            return;
        }

        EmitSimpleBinding(indent, property, local);
    }

    private static void EmitLocalDeclaration(
        IndentedStringBuilder indent,
        BoundProperty property,
        string local,
        string typeName)
    {
        if (property.IsCollection)
        {
            var listType = $"global::System.Collections.Generic.List<{typeName}>";
            indent.AppendLine($"{listType} {local} = new {listType}();");
            return;
        }

        if (property.IsComplex && !property.IsNullable)
        {
            indent.AppendLine($"{typeName} {local} = null!;");
            return;
        }

        if (property.IsNullable || property.IsString)
        {
            indent.AppendLine($"{typeName} {local} = null!;");
            return;
        }

        indent.AppendLine($"{typeName} {local} = default;");
    }

    private static void EmitSimpleBinding(
        IndentedStringBuilder indent,
        BoundProperty property,
        string local)
    {
        var rawVar = $"{local}Raw";
        EmitValueAccessor(indent, property, rawVar);
        EmitValueParser(indent, property, local, rawVar);
    }

    private static void EmitValueAccessor(
        IndentedStringBuilder indent,
        BoundProperty property,
        string rawVar)
    {
        var key = property.KeyName;
        var local = ToCamelCase(property.Name);

        switch (property.HttpBinderType)
        {
            case HttpBinderType.Query:
                indent.AppendLine(
                    $"var {rawVar} = query.TryGetValue(\"{key}\", out var {local}QueryValue) && {local}QueryValue.Count > 0 ? {local}QueryValue.ToString() : null;");
                break;

            case HttpBinderType.Route:
                indent.AppendLine(
                    $"var {rawVar} = route.TryGetValue(\"{key}\", out var {local}RouteValue) ? {local}RouteValue?.ToString() : null;");
                break;

            default:
                indent.AppendLine(
                    $"var {rawVar} = form.TryGetValue(\"{key}\", out var {local}FormValue) && {local}FormValue.Count > 0 ? {local}Value.ToString() : null;");
                break;
        }
    }

    private static void EmitValueParser(
        IndentedStringBuilder indent,
        BoundProperty property,
        string local,
        string rawVar)
    {
        var parsed = $"{local}Parsed";

        if (property.IsString)
        {
            indent.AppendLine($"if ({rawVar} != null) {local} = {rawVar};");
            return;
        }

        if (property.IsGuid)
        {
            indent.AppendLine($"if ({rawVar} != null && global::System.Guid.TryParse({rawVar}, out var {parsed})) {local} = {parsed};");
            return;
        }

        if (property.IsEnum)
        {
            indent.AppendLine($"if ({rawVar} != null && global::System.Enum.TryParse<{property.TypeName}>({rawVar}, true, out var {parsed})) {local} = {parsed};");
            return;
        }

        if (property.IsPrimitive)
        {
            indent.AppendLine($"if ({rawVar} != null && {GetTryParseMethod(property.TypeName)}({rawVar}, out var {parsed})) {local} = {parsed};");
            return;
        }
    }

    private static void EmitComplexCall(
        IndentedStringBuilder indent,
        BoundProperty property,
        string local,
        bool requiresForm)
    {
        var helper = $"Bind_{Sanitize(property.TypeName)}";
        var formArg = requiresForm ? "form" : "null";
        indent.AppendLine($"{local} = {helper}(http, \"{property.KeyName}.\", {formArg});");
    }

    private static void GenerateCollectionBinding(
        IndentedStringBuilder indent,
        BoundProperty property,
        string local,
        bool requiresForm)
    {
        var elementType = property.TypeName;

        // keys source
        var keys = property.HttpBinderType switch
        {
            HttpBinderType.Query => "query.Keys",
            HttpBinderType.Route => "route.Keys",
            _ => "form.Keys"
        };

        indent.AppendLine($"var {local}Prefix = \"{property.KeyName}[\";");

        indent.AppendLine($"foreach (var key in {keys})");
        indent.AppendLine("{");
        indent.Indent();

        indent.AppendLine($"if (!key.StartsWith({local}Prefix)) continue;");
        indent.AppendLine($"var idxStart = {local}Prefix.Length;");
        indent.AppendLine("var idxEnd = key.IndexOf(']', idxStart);");
        indent.AppendLine("if (idxEnd < 0) continue;");
        indent.AppendLine("var idxText = key.Substring(idxStart, idxEnd - idxStart);");
        indent.AppendLine($"if (!int.TryParse(idxText, out var index)) continue;");
        indent.AppendLine($"while ({local}.Count <= index) {local}.Add(default!);");

        if (property.IsComplex)
        {
            var helper = $"Bind_{Sanitize(elementType)}";
            var formArg = requiresForm ? "form" : "null";
            indent.AppendLine($"{local}[index] = {helper}(http, key + \".\", {formArg});");
        }
        else
        {
            EmitCollectionElementBinding(indent, local, elementType, property.HttpBinderType, "index");
        }

        indent.Unindent();
        indent.AppendLine("}");
    }

    private static void EmitCollectionElementBinding(
        IndentedStringBuilder indent,
        string local,
        string elementType,
        HttpBinderType source,
        string indexExpr)
    {
        var raw = $"{local}ElementRaw";

        indent.AppendLine($"string? {raw} = null;");

        switch (source)
        {
            case HttpBinderType.Query:
                indent.AppendLine($"if (query.TryGetValue(key, out var queryValue) && queryValue.Count > 0) {raw} = queryValue.ToString();");
                break;

            case HttpBinderType.Route:
                indent.AppendLine($"if (route.TryGetValue(key, out var routeValue)) {raw} = routeValue?.ToString();");
                break;

            default:
                indent.AppendLine($"if (form.TryGetValue(key, out var formValue) && fv.Count > 0) {raw} = formValue.ToString();");
                break;
        }

        if (elementType == "string" || elementType == "global::System.String")
        {
            indent.AppendLine($"if ({raw} != null) {local}[{indexExpr}] = {raw};");
            return;
        }

        var parsed = $"{local}ElementParsed";

        if (elementType == "global::System.Guid")
        {
            indent.AppendLine($"if ({raw} != null && global::System.Guid.TryParse({raw}, out var {parsed})) {local}[{indexExpr}] = {parsed};");
            return;
        }

        if (elementType.Contains("enum"))
        {
            indent.AppendLine($"if ({raw} != null && global::System.Enum.TryParse<{elementType}>({raw}, true, out var {parsed})) {local}[{indexExpr}] = {parsed};");
            return;
        }

        indent.AppendLine($"if ({raw} != null && {GetTryParseMethod(elementType)}({raw}, out var {parsed})) {local}[{indexExpr}] = {parsed};");
    }

    private static void RenderComplexHelpers(IndentedStringBuilder indent, BoundType model)
    {
        var emitted = new HashSet<string>();

        foreach (var p in model.Properties)
            Walk(p);

        void Walk(BoundProperty p)
        {
            if (p.IsComplex && !p.IsCollection && emitted.Add(p.TypeName))
                RenderComplexHelper(indent, p.TypeName, p.ChildProperties);

            if (p.IsComplex && p.IsCollection && emitted.Add(p.TypeName))
                RenderComplexHelper(indent, p.TypeName, p.ChildProperties);

            foreach (var c in p.ChildProperties)
                Walk(c);
        }
    }

    private static void RenderComplexHelper(
        IndentedStringBuilder indent,
        string typeName,
        ImmutableArray<BoundProperty> properties)
    {
        var helper = $"Bind_{Sanitize(typeName)}";

        indent.AppendLine($"private static {typeName} {helper}(");
        indent.AppendLine("    global::Microsoft.AspNetCore.Http.HttpContext http,");
        indent.AppendLine("    string prefix,");
        indent.AppendLine("    global::Microsoft.AspNetCore.Http.IFormCollection? form)");
        indent.AppendLine("{");
        indent.Indent();

        foreach (var property in properties)
        {
            var local = ToCamelCase(property.Name);
            if (property.IsCollection)
            {
                var listType = $"global::System.Collections.Generic.List<{property.TypeName}>";
                indent.AppendLine($"{listType} {local} = new {listType}();");
            }
            else if (property.IsNullable || property.IsString)
            {
                indent.AppendLine($"{property.TypeName} {local} = null;");
            }
            else
            {
                indent.AppendLine($"{property.TypeName} {local} = default;");
            }
        }

        indent.AppendLine();

        foreach (var property in properties)
        {
            var local = ToCamelCase(property.Name);
            var keyVar = $"{local}Key";
            indent.AppendLine($"var {keyVar} = prefix + \"{property.KeyName}\";");

            if (property.IsCollection)
            {
                EmitComplexChildCollection(indent, property, local, keyVar);
            }
            else if (property.IsComplex)
            {
                var nested = $"Bind_{Sanitize(property.TypeName)}";
                indent.AppendLine($"{local} = {nested}(http, {keyVar} + \".\", form);");
            }
            else
            {
                EmitComplexChildSimple(indent, property, local, keyVar);
            }

            indent.AppendLine();
        }

        indent.AppendLine($"var instance = new {typeName}();");

        foreach (var c in properties)
        {
            var local = ToCamelCase(c.Name);
            indent.AppendLine($"instance.{c.Name} = {local};");
        }

        indent.AppendLine("return instance;");
        indent.Unindent();
        indent.AppendLine("}");
    }

    private static void EmitComplexChildSimple(
        IndentedStringBuilder indent,
        BoundProperty c,
        string local,
        string keyVar)
    {
        var raw = $"{local}Raw";
        indent.AppendLine($"var {raw} = form != null && form.TryGetValue({keyVar}, out var temp{local}) && temp{local}.Count > 0 ? temp{local}.ToString() : null;");
        EmitValueParser(indent, c, local, raw);
    }

    private static void EmitComplexChildCollection(
        IndentedStringBuilder indent,
        BoundProperty property,
        string local,
        string keyVar)
    {
        var prefixVar = $"{local}Prefix";
        indent.AppendLine($"var {prefixVar} = {keyVar} + \"[\";");

        indent.AppendLine("foreach (var key in form?.Keys ?? global::System.Array.Empty<string>())");
        indent.AppendLine("{");
        indent.Indent();

        indent.AppendLine($"if (!key.StartsWith({prefixVar})) continue;");
        indent.AppendLine($"var idxStart = {prefixVar}.Length;");
        indent.AppendLine("var idxEnd = key.IndexOf(']', idxStart);");
        indent.AppendLine("if (idxEnd < 0) continue;");
        indent.AppendLine("var idxText = key.Substring(idxStart, idxEnd - idxStart);");
        indent.AppendLine($"if (!int.TryParse(idxText, out var index)) continue;");
        indent.AppendLine($"while ({local}.Count <= index) {local}.Add(default!);");

        if (property.IsComplex)
        {
            var nested = $"Bind_{Sanitize(property.TypeName)}";
            indent.AppendLine($"{local}[index] = {nested}(http, key + \".\", form);");
        }
        else
        {
            EmitCollectionElementBinding(indent, local, property.TypeName, property.HttpBinderType, "index");
        }

        indent.Unindent();
        indent.AppendLine("}");
    }

    private static string GetTryParseMethod(string typeName) =>
        typeName switch
        {
            "global::System.Boolean" => "bool.TryParse",
            "global::System.Byte" => "byte.TryParse",
            "global::System.SByte" => "sbyte.TryParse",
            "global::System.Int16" => "short.TryParse",
            "global::System.UInt16" => "ushort.TryParse",
            "global::System.Int32" => "int.TryParse",
            "global::System.UInt32" => "uint.TryParse",
            "global::System.Int64" => "long.TryParse",
            "global::System.UInt64" => "ulong.TryParse",
            "global::System.Single" => "float.TryParse",
            "global::System.Double" => "double.TryParse",
            "global::System.Decimal" => "decimal.TryParse",
            _ => "int.TryParse"
        };

    private static string Sanitize(string fullTypeName)
    {
        fullTypeName = fullTypeName.Replace("global::", "");
        var sb = new StringBuilder(fullTypeName.Length);
        foreach (var c in fullTypeName)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }

    private static string ToCamelCase(string name) =>
        string.IsNullOrEmpty(name)
            ? name
            : char.ToLowerInvariant(name[0]) + name.Substring(1);
}
