using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Text;

namespace Blueprint.HttpBinder;

/// <summary>
/// Emits the generated binder source for a DTO bound via BindAsync().
/// The renderer prioritizes human readability of the generated code.
/// </summary>
internal static class CodeRenderer
{
    public static string Render(BoundType model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = model.TypeSymbol.ContainingNamespace.ToDisplayString();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");

        var indent = new IndentedStringBuilder(sb, 1);

        var typeKind = model.TypeSymbol.IsRecord ? "record" : "class";
        indent.AppendLine($"partial {typeKind} {model.TypeSymbol.Name}");
        indent.AppendLine("{");
        indent.Indent();

        RenderBindMethod(indent, model);
        indent.AppendLine();
        RenderComplexHelpers(indent, model);

        indent.Unindent();
        indent.AppendLine("}");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void RenderBindMethod(IndentedStringBuilder indent, BoundType model)
    {
        var typeName = Utilities.GetFullTypeName(model.TypeSymbol);
        var requiresForm = RequiresForm(model);
        var usesQuery = UsesQueryAtRoot(model);
        var usesRoute = UsesRouteAtRoot(model);

        indent.AppendLine(
            $"public static async global::System.Threading.Tasks.ValueTask<{typeName}> BindAsync(");
        indent.AppendLine("    global::Microsoft.AspNetCore.Http.HttpContext http)");
        indent.AppendLine("{");
        indent.Indent();

        indent.AppendLine("var request = http.Request;");

        if (requiresForm)
            indent.AppendLine("var form = await request.ReadFormAsync().ConfigureAwait(false);");

        if (usesQuery)
            indent.AppendLine("var query = request.Query;");

        if (usesRoute)
            indent.AppendLine("var route = request.RouteValues;");

        indent.AppendLine();

        foreach (var property in model.Properties)
        {
            GeneratePropertyBinding(indent, property, requiresForm);
            indent.AppendLine();
        }

        indent.AppendLine($"var instance = new {typeName}();");

        foreach (var property in model.Properties)
        {
            var localName = ToCamelCase(property.Name);
            indent.AppendLine($"instance.{property.Name} = {localName};");
        }

        indent.AppendLine("return instance;");

        indent.Unindent();
        indent.AppendLine("}");
    }

    private static bool RequiresForm(BoundType model)
    {
        foreach (var property in model.Properties)
        {
            if (RequiresFormRecursive(property))
                return true;
        }

        return false;

        static bool RequiresFormRecursive(BoundProperty property)
        {
            if (property.HttpBinderType == HttpBinderType.Form)
                return true;

            foreach (var child in property.Children)
            {
                if (RequiresFormRecursive(child))
                    return true;
            }

            return false;
        }
    }

    private static bool UsesQueryAtRoot(BoundType model)
    {
        foreach (var property in model.Properties)
        {
            // Only simple props / simple collections bind from query
            if (!property.IsComplex && property.HttpBinderType == HttpBinderType.Query)
                return true;

            if (property.IsCollection && !property.IsComplex && property.HttpBinderType == HttpBinderType.Query)
                return true;
        }

        return false;
    }

    private static bool UsesRouteAtRoot(BoundType model)
    {
        foreach (var property in model.Properties)
        {
            if (!property.IsComplex && property.HttpBinderType == HttpBinderType.Route)
                return true;

            if (property.IsCollection && !property.IsComplex && property.HttpBinderType == HttpBinderType.Route)
                return true;
        }

        return false;
    }

    private static void GeneratePropertyBinding(
        IndentedStringBuilder indent,
        BoundProperty property,
        bool requiresForm)
    {
        var localName = ToCamelCase(property.Name);
        var typeName = Utilities.GetFullTypeName(property.Symbol.Type);

        EmitLocalDeclaration(indent, property, localName, typeName);

        if (property.IsCollection)
        {
            GenerateCollectionBinding(indent, property, localName, requiresForm);
            return;
        }

        if (property.IsComplex)
        {
            EmitComplexCall(indent, property, localName, requiresForm);
            return;
        }

        EmitSimpleBinding(indent, property, localName, requiresForm);
    }

    private static void EmitLocalDeclaration(
        IndentedStringBuilder indent,
        BoundProperty property,
        string localName,
        string typeName)
    {
        if (property.IsCollection)
        {
            indent.AppendLine($"{typeName} {localName} = new {typeName}();");
            return;
        }

        if (property.Symbol.Type.IsReferenceType)
        {
            indent.AppendLine($"{typeName}? {localName} = null;");
            return;
        }

        indent.AppendLine($"{typeName} {localName} = default;");
    }

    private static void EmitSimpleBinding(
        IndentedStringBuilder indent,
        BoundProperty property,
        string localName,
        bool requiresForm)
    {
        var rawVar = $"{localName}Raw";

        EmitValueAccessor(indent, property, localName, rawVar, requiresForm);
        EmitValueParser(indent, property, localName, rawVar);
    }

    private static void EmitValueAccessor(
        IndentedStringBuilder indent,
        BoundProperty property,
        string baseName,
        string rawVar,
        bool requiresForm)
    {
        var key = property.KeyName;
        var name = baseName;

        var formValueVar = $"{name}FormValue";
        var queryValueVar = $"{name}QueryValue";
        var routeValueVar = $"{name}RouteValue";

        switch (property.HttpBinderType)
        {
            case HttpBinderType.Query:
                indent.AppendLine(
                    $"var {rawVar} = query.TryGetValue(\"{key}\", out var {queryValueVar}) && {queryValueVar}.Count > 0");
                indent.AppendLine($"    ? {queryValueVar}.ToString()");
                indent.AppendLine("    : null;");
                break;

            case HttpBinderType.Route:
                indent.AppendLine(
                    $"var {rawVar} = route.TryGetValue(\"{key}\", out var {routeValueVar})");
                indent.AppendLine($"    ? {routeValueVar}?.ToString()");
                indent.AppendLine("    : null;");
                break;

            case HttpBinderType.Form:
            default:
                if (requiresForm)
                {
                    indent.AppendLine(
                        $"var {rawVar} = form.TryGetValue(\"{key}\", out var {formValueVar}) && {formValueVar}.Count > 0");
                    indent.AppendLine($"    ? {formValueVar}.ToString()");
                    indent.AppendLine("    : null;");
                }
                else
                {
                    indent.AppendLine(
                        $"var {rawVar} = http.Request.Form.TryGetValue(\"{key}\", out var {formValueVar}) && {formValueVar}.Count > 0");
                    indent.AppendLine($"    ? {formValueVar}.ToString()");
                    indent.AppendLine("    : null;");
                }
                break;
        }
    }

    private static void EmitValueParser(
        IndentedStringBuilder indent,
        BoundProperty property,
        string localName,
        string rawVar)
    {
        if (property.IsString)
        {
            indent.AppendLine($"if ({rawVar} != null) {localName} = {rawVar};");
            return;
        }

        if (property.IsGuid)
        {
            indent.AppendLine(
                $"if ({rawVar} != null && global::System.Guid.TryParse({rawVar}, out var {localName}Parsed))");
            indent.AppendLine($"    {localName} = {localName}Parsed;");
            return;
        }

        if (property.IsEnum)
        {
            var enumName = Utilities.GetFullTypeName(property.Symbol.Type);

            indent.AppendLine(
                $"if ({rawVar} != null && global::System.Enum.TryParse<{enumName}>({rawVar}, true, out var {localName}Parsed))");
            indent.AppendLine($"    {localName} = {localName}Parsed;");
            return;
        }

        if (property.IsPrimitive)
        {
            var parse = GetTryParseMethod(property.Symbol.Type);

            indent.AppendLine(
                $"if ({rawVar} != null && {parse}({rawVar}, out var {localName}Parsed))");
            indent.AppendLine($"    {localName} = {localName}Parsed;");
            return;
        }

        indent.AppendLine($"// Unsupported type: {Utilities.GetFullTypeName(property.Symbol.Type)}");
    }

    private static void EmitComplexCall(
        IndentedStringBuilder indent,
        BoundProperty property,
        string localName,
        bool requiresForm)
    {
        var helperName = $"Bind_{GetSanitizedTypeName(property.Symbol.Type)}";
        var formArg = requiresForm ? "form" : "null";
        var prefix = property.KeyName + ".";

        indent.AppendLine(
            $"{localName} = {helperName}(http, \"{prefix}\", {formArg});");
    }

    // ==================================================================
    //  Collection binding (root and complex)
    // ==================================================================

    private static void GenerateCollectionBinding(
        IndentedStringBuilder indent,
        BoundProperty property,
        string localName,
        bool requiresForm)
    {
        var listName = localName;
        var elementType = property.CollectionType!;
        var keyBase = property.KeyName;

        var keysExpr =
            property.HttpBinderType == HttpBinderType.Query ? "query.Keys" :
            property.HttpBinderType == HttpBinderType.Route ? "route.Keys" :
            requiresForm ? "form.Keys" :
            "http.Request.Form.Keys";

        indent.AppendLine($"var {listName}Key = \"{keyBase}\";");
        indent.AppendLine($"var {listName}Prefix = {listName}Key + \"[\";");
        indent.AppendLine();

        indent.AppendLine($"foreach (var key in {keysExpr})");
        indent.AppendLine("{");
        indent.Indent();

        indent.AppendLine(
            $"if (!key.StartsWith({listName}Prefix, global::System.StringComparison.OrdinalIgnoreCase))");
        indent.AppendLine("    continue;");

        indent.AppendLine("var indexStart = " + listName + "Prefix.Length;");
        indent.AppendLine("var indexEnd = key.IndexOf(']', indexStart);");
        indent.AppendLine("if (indexEnd < 0) continue;");

        indent.AppendLine("var indexText = key.Substring(indexStart, indexEnd - indexStart);");
        indent.AppendLine("if (!int.TryParse(indexText, out var index)) continue;");

        indent.AppendLine($"while ({listName}.Count <= index)");
        indent.AppendLine($"    {listName}.Add(default!);");

        indent.AppendLine("var elementKey = key;");

        var elementIsSimple = IsSimpleElementType(elementType);

        if (!elementIsSimple)
        {
            if (property.HttpBinderType == HttpBinderType.Form)
            {
                var helperName = $"Bind_{GetSanitizedTypeName(elementType)}";
                var formArg = requiresForm ? "form" : "null";

                indent.AppendLine(
                    $"{listName}[index] = {helperName}(http, elementKey + \".\", {formArg});");
            }
            else
            {
                indent.AppendLine(
                    $"// Complex collection bound from {property.HttpBinderType} is unsupported.");
            }
        }
        else
        {
            EmitCollectionElementBinding(
                indent,
                listName,
                listName,
                elementType,
                property.HttpBinderType,
                $"{localName}Index");
        }

        indent.Unindent();
        indent.AppendLine("}");
    }

    private static void EmitCollectionElementBinding(
        IndentedStringBuilder indent,
        string listName,
        string baseName,
        ITypeSymbol elementType,
        HttpBinderType binderType,
        string indexName)
    {
        var rawVar = $"{ToCamelCase(baseName)}ElementRaw";
        var formValueVar = $"{ToCamelCase(baseName)}ElementFormValue";
        var queryValueVar = $"{ToCamelCase(baseName)}ElementQueryValue";
        var routeValueVar = $"{ToCamelCase(baseName)}ElementRouteValue";

        indent.AppendLine();
        indent.AppendLine($"string? {rawVar} = null;");

        switch (binderType)
        {
            case HttpBinderType.Query:
                indent.AppendLine(
                    $"if (query.TryGetValue(elementKey, out var {queryValueVar}) && {queryValueVar}.Count > 0)");
                indent.AppendLine($"    {rawVar} = {queryValueVar}.ToString();");
                break;

            case HttpBinderType.Route:
                indent.AppendLine(
                    $"if (route.TryGetValue(elementKey, out var {routeValueVar}))");
                indent.AppendLine($"    {rawVar} = {routeValueVar}?.ToString();");
                break;

            case HttpBinderType.Form:
            default:
                indent.AppendLine(
                    $"if (form!.TryGetValue(elementKey, out var {formValueVar}) && {formValueVar}.Count > 0)");
                indent.AppendLine($"    {rawVar} = {formValueVar}.ToString();");
                break;
        }

        indent.AppendLine();

        var full = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (full == "global::System.String")
        {
            indent.AppendLine($"if ({rawVar} != null) {listName}[index] = {rawVar};");
            return;
        }

        if (full == "global::System.Guid")
        {
            indent.AppendLine(
                $"if ({rawVar} != null && global::System.Guid.TryParse({rawVar}, out var elementParsed))");
        }
        else if (elementType is INamedTypeSymbol enumType && enumType.TypeKind == TypeKind.Enum)
        {
            var enumName = Utilities.GetFullTypeName(elementType);

            indent.AppendLine(
                $"if ({rawVar} != null && global::System.Enum.TryParse<{enumName}>({rawVar}, true, out var elementParsed))");
        }
        else
        {
            var parse = GetTryParseMethod(elementType);

            indent.AppendLine(
                $"if ({rawVar} != null && {parse}({rawVar}, out var elementParsed))");
        }


        indent.AppendLine($"    {listName}[{indexName}] = elementParsed;");
    }

    private static void RenderComplexHelpers(IndentedStringBuilder indent, BoundType model)
    {
        var emitted = new HashSet<string>(StringComparer.Ordinal);

        void Process(BoundProperty property)
        {
            if (property.IsComplex && !property.IsCollection)
            {
                var key = GetSanitizedTypeName(property.Symbol.Type);
                if (emitted.Add(key))
                    RenderComplexHelper(indent, property.Symbol.Type, property.Children);
            }

            if (property.IsCollection &&
                property.CollectionType is ITypeSymbol element &&
                NeedsComplexHelper(element))
            {
                var key = GetSanitizedTypeName(element);
                if (emitted.Add(key))
                    RenderComplexHelper(indent, element, property.Children);
            }

            foreach (var child in property.Children)
                Process(child);
        }

        foreach (var property in model.Properties)
            Process(property);
    }

    private static bool NeedsComplexHelper(ITypeSymbol type)
    {
        return !IsSimpleElementType(type);
    }

    private static void RenderComplexHelper(
        IndentedStringBuilder indent,
        ITypeSymbol type,
        List<BoundProperty> children)
    {
        var typeName = Utilities.GetFullTypeName(type);
        var helperName = $"Bind_{GetSanitizedTypeName(type)}";

        indent.AppendLine($"private static {typeName} {helperName}(");
        indent.AppendLine("    global::Microsoft.AspNetCore.Http.HttpContext http,");
        indent.AppendLine("    string prefix,");
        indent.AppendLine("    global::Microsoft.AspNetCore.Http.IFormCollection? form)");
        indent.AppendLine("{");
        indent.Indent();

        // locals
        foreach (var child in children)
        {
            var localName = ToCamelCase(child.Name);
            var childType = Utilities.GetFullTypeName(child.Symbol.Type);

            if (child.IsCollection)
            {
                indent.AppendLine($"{childType} {localName} = new {childType}();");
            }
            else
            {
                var initializer =
                    (child.IsNullable || child.Symbol.Type.IsReferenceType)
                        ? "default!"
                        : "default";

                indent.AppendLine($"{childType} {localName} = {initializer};");
            }
        }

        indent.AppendLine();

        // binding
        foreach (var child in children)
        {
            var localName = ToCamelCase(child.Name);
            var keyVar = $"{localName}Key";

            indent.AppendLine($"// {child.Name}");
            indent.AppendLine($"var {keyVar} = prefix + \"{child.KeyName}\";");
            indent.AppendLine();

            if (child.IsCollection)
            {
                EmitComplexChildCollection(indent, child, localName, keyVar);
            }
            else if (child.IsComplex)
            {
                var nestedHelper = $"Bind_{GetSanitizedTypeName(child.Symbol.Type)}";
                indent.AppendLine(
                    $"{localName} = {nestedHelper}(http, {keyVar} + \".\", form);");
            }
            else
            {
                EmitComplexChildSimple(indent, child, localName, keyVar);
            }

            indent.AppendLine();
        }

        var instanceName = "instance";
        indent.AppendLine($"var {instanceName} = new {typeName}();");

        foreach (var child in children)
        {
            var localName = ToCamelCase(child.Name);
            indent.AppendLine($"{instanceName}.{child.Name} = {localName};");
        }

        indent.AppendLine($"return {instanceName};");

        indent.Unindent();
        indent.AppendLine("}");
    }

    private static void EmitComplexChildSimple(
        IndentedStringBuilder indent,
        BoundProperty child,
        string localName,
        string keyVar)
    {
        var rawVar = $"{localName}Raw";
        var formValueVar = $"{localName}FormValue";

        indent.AppendLine(
            $"var {rawVar} = form != null && form.TryGetValue({keyVar}, out var {formValueVar}) && {formValueVar}.Count > 0");
        indent.AppendLine($"    ? {formValueVar}.ToString()");
        indent.AppendLine("    : null;");

        EmitValueParser(indent, child, localName, rawVar);
    }

    private static void EmitComplexChildCollection(
        IndentedStringBuilder indent,
        BoundProperty child,
        string localName,
        string keyVar)
    {
        var prefixVar = $"{localName}Prefix";

        indent.AppendLine($"var {prefixVar} = {keyVar} + \"[\";");
        indent.AppendLine();

        indent.AppendLine("foreach (var key in form?.Keys ?? global::System.Array.Empty<string>())");
        indent.AppendLine("{");
        indent.Indent();

        indent.AppendLine(
            $"if (!key.StartsWith({prefixVar}, global::System.StringComparison.OrdinalIgnoreCase))");
        indent.AppendLine("    continue;");

        indent.AppendLine($"var {localName}IndexStart = {prefixVar}.Length;");
        indent.AppendLine($"var {localName}IndexEnd = key.IndexOf(']', {localName}IndexStart);");
        indent.AppendLine($"if ({localName}IndexEnd < 0) continue;");

        indent.AppendLine(
            $"var {localName}IndexString = key.Substring({localName}IndexStart, {localName}IndexEnd - {localName}IndexStart);");
        indent.AppendLine($"if (!int.TryParse({localName}IndexString, out var {localName}Index)) continue;");

        indent.AppendLine(
            $"while ({localName}.Count <= {localName}Index)");
        indent.AppendLine($"    {localName}.Add(default!);");

        indent.AppendLine("var elementKey = key;");

        if (child.CollectionType is ITypeSymbol elementType)
        {
            var elementIsSimple = IsSimpleElementType(elementType);

            if (!elementIsSimple)
            {
                var nestedHelper = $"Bind_{GetSanitizedTypeName(elementType)}";
                indent.AppendLine(
                    $"{localName}[{localName}Index] = {nestedHelper}(http, elementKey + \".\", form);");
            }
            else
            {
                EmitCollectionElementBinding(
                    indent,
                    localName,
                    localName,
                    elementType,
                    child.HttpBinderType,
                    $"{localName}Index");
            }
        }

        indent.Unindent();
        indent.AppendLine("}");
    }

    private static string GetSanitizedTypeName(ITypeSymbol type)
    {
        var raw = Utilities.GetMinimalTypeName(type);
        var sb = new StringBuilder(raw.Length);

        foreach (var ch in raw)
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');

        return sb.ToString();
    }

    private static string GetTryParseMethod(ITypeSymbol type)
    {
        var full = Utilities.GetFullTypeName(type);

        return full switch
        {
            "global::System.Boolean" => "bool.TryParse",
            "global::System.Byte" => "byte.TryParse",
            "global::System.SByte" => "sbyte.TryParse",
            "global::System.Int16" => "short.TryParse",
            "global::System.UInt16" => "ushort.TryParse",
            "global::System.Int32" => "int.TryParse",
            "global::System.UInt32" => "uint.TryParse",
            "global::System.Int64" => "long.TryParse",
            "global::System.UInt64" => "ulong.TryParse",
            "global::System.Single" => "float.TryParse",
            "global::System.Double" => "double.TryParse",
            "global::System.Decimal" => "decimal.TryParse",
            _ => "int.TryParse"
        };
    }

    private static bool IsSimpleElementType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named &&
            named.IsGenericType &&
            named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            type = named.TypeArguments[0];
        }

        if (type.SpecialType == SpecialType.System_String)
            return true;

        if (type is INamedTypeSymbol namedEnum && namedEnum.TypeKind == TypeKind.Enum)
            return true;

        var full = Utilities.GetFullTypeName(type);
        if (full == "global::System.Guid")
            return true;

        if (type.SpecialType is
            SpecialType.System_Boolean or
            SpecialType.System_Byte or
            SpecialType.System_SByte or
            SpecialType.System_Int16 or
            SpecialType.System_UInt16 or
            SpecialType.System_Int32 or
            SpecialType.System_UInt32 or
            SpecialType.System_Int64 or
            SpecialType.System_UInt64 or
            SpecialType.System_Single or
            SpecialType.System_Double or
            SpecialType.System_Decimal or
            SpecialType.System_Char)
        {
            return true;
        }

        return false;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;

        if (char.IsLower(name[0]))
            return name;

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
